'use client';

import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { loadAssignmentActivityProgress, saveAssignmentActivityProgress } from '@/lib/assignmentProgressClient';

export type LessonSection = { heading: string; body: string; question?: string; taskType?: string };
type Props = { activityId: string; sections: LessonSection[]; nextHref?: string; pathwayHref: string };
function countWords(value: string) { return value.trim().length === 0 ? 0 : value.trim().split(/\s+/).length; }

export default function LessonContentActivity({ activityId, sections, nextHref, pathwayHref }: Props) {
  const router = useRouter(); const searchParams = useSearchParams(); const assignmentId = searchParams.get('assignment');
  const [summary,setSummary]=useState(''); const [hydrated,setHydrated]=useState(!assignmentId); const [saveStatus,setSaveStatus]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const [error,setError]=useState(''); const [navigating,setNavigating]=useState(false);
  const wordCount=useMemo(()=>countWords(summary),[summary]); const tooLong=wordCount>90; const complete=wordCount>0&&!tooLong;

  useEffect(()=>{ if(!assignmentId)return; let cancelled=false; void loadAssignmentActivityProgress(assignmentId,'lesson_content').then((progress)=>{ if(cancelled||!progress)return; const position=progress.position??{}; if(typeof position.lessonSummary==='string')setSummary(position.lessonSummary); setSaveStatus('saved'); }).catch(()=>undefined).finally(()=>{if(!cancelled)setHydrated(true);}); return()=>{cancelled=true;}; },[assignmentId]);

  async function saveSummary(nextSummary=summary){ const nextWordCount=countWords(nextSummary); if(nextWordCount===0)return true; const status=nextWordCount>90?'in_progress':'complete'; setSaveStatus('saving');setError(''); try{ if(assignmentId){await saveAssignmentActivityProgress({assignmentId,activityType:'lesson_content',status,position:{lessonSummary:nextSummary,summaryWordCount:nextWordCount,completedVia:'lesson_summary'}});}else{const response=await fetch('/api/student-responses/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activityId,responseType:'lesson_content',status,response:{lessonSummary:nextSummary,summaryWordCount:nextWordCount,completedVia:'lesson_summary'}}),keepalive:true});const result=await response.json().catch(()=>null);if(!response.ok)throw new Error(result?.error??'Your lesson summary could not be saved.');} setSaveStatus('saved');return true;}catch(caught){setSaveStatus('error');setError(caught instanceof Error?caught.message:'Your lesson summary could not be saved.');return false;}}
  useEffect(()=>{if(!hydrated||!summary.trim())return;const timeout=window.setTimeout(()=>{void saveSummary(summary);},650);return()=>window.clearTimeout(timeout);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[summary,hydrated]);
  async function navigateTo(href:string){if(navigating)return;setNavigating(true);if(summary.trim()){const saved=await saveSummary(summary);if(!saved){setNavigating(false);return;}}router.push(href);}

  if(!sections.length)return <section className="card warm"><h1>No lesson content found</h1><p>This pathway does not currently have any lesson sections.</p></section>;
  return <section style={{display:'grid',gap:18}}>
    {sections.map((section,index)=><article key={`${section.heading}-${index}`} style={{border:'1px solid rgba(213, 226, 235, 0.95)',borderRadius:24,background:'rgba(255, 255, 255, 0.86)',padding:'20px',boxShadow:'0 10px 26px rgba(22, 33, 63, 0.06)'}}><p style={{margin:0,color:'var(--muted)',fontSize:13,fontWeight:900,letterSpacing:'0.12em',textTransform:'uppercase'}}>Section {index+1}</p><h2 style={{margin:'8px 0 10px',color:'var(--navy)'}}>{section.heading}</h2><p style={{margin:0,lineHeight:1.7,color:'var(--navy)'}}>{section.body}</p>{section.question&&<div style={{marginTop:16,borderRadius:18,background:'rgba(238, 244, 249, 0.95)',padding:'14px 16px'}}><strong style={{display:'block',marginBottom:6,color:'var(--navy)'}}>Check your understanding</strong><p style={{margin:0,color:'var(--navy)'}}>{section.question}</p></div>}</article>)}
    <section style={{border:'1px solid rgba(213, 226, 235, 0.95)',borderRadius:24,background:'rgba(255, 255, 255, 0.9)',padding:'20px',boxShadow:'0 10px 26px rgba(22, 33, 63, 0.06)',display:'grid',gap:12}}><div><p style={{margin:0,color:'var(--muted)',fontSize:13,fontWeight:900,letterSpacing:'0.12em',textTransform:'uppercase'}}>Final task</p><h2 style={{margin:'8px 0 8px',color:'var(--navy)'}}>Summarise the lesson notes</h2><p style={{margin:0,lineHeight:1.6,color:'var(--navy)'}}>Summarise the most important ideas from these lesson notes in no more than 90 words. Focus on what you would need to remember later.</p></div>
      <textarea value={summary} onChange={(event)=>setSummary(event.target.value)} placeholder="Write your summary here..." rows={7} aria-label="Lesson notes summary" style={{width:'100%',resize:'vertical',minHeight:150,border:tooLong?'2px solid #b94747':'1px solid rgba(213, 226, 235, 0.95)',borderRadius:18,padding:'14px 16px',font:'inherit',lineHeight:1.6,color:'var(--navy)',background:'white',boxSizing:'border-box'}} />
      <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><span style={{color:tooLong?'#9f3434':'var(--muted)',fontWeight:800}}>{wordCount}/90 words{tooLong?' — shorten your summary to complete the activity':''}</span><span style={{color:saveStatus==='error'?'#9f3434':'var(--muted)',fontWeight:800}}>{saveStatus==='saving'?'Saving automatically...':saveStatus==='saved'?(complete?'Saved · lesson complete':'Saved draft') : saveStatus==='error'?error:'Autosave on'}</span></div>
      <div style={{display:'grid',gridTemplateColumns:nextHref?'1fr 1fr':'1fr',gap:10}}><button type="button" onClick={()=>void navigateTo(pathwayHref)} disabled={navigating} style={{minHeight:52,borderRadius:999,padding:'12px 18px',border:'1px solid rgba(213, 226, 235, 0.95)',background:'white',color:'var(--navy)',fontWeight:950,cursor:navigating?'wait':'pointer'}}>Back to pathway</button>{nextHref&&<button type="button" onClick={()=>void navigateTo(nextHref)} disabled={!complete||navigating} style={{minHeight:52,borderRadius:999,padding:'12px 18px',border:0,background:'var(--navy)',color:'white',fontWeight:950,opacity:complete?1:0.48,cursor:complete&&!navigating?'pointer':'not-allowed'}}>{navigating?'Saving...':'Next activity →'}</button>}</div>
    </section>
  </section>;
}
