export type PathwayStatus = 'ready' | 'planned';
export type YearGroup = 'Y12' | 'Y13';

export type BreadthLens =
  | 'governance'
  | 'opposition'
  | 'economy'
  | 'society'
  | 'ideology'
  | 'individuals';

export type WrittenFocusType =
  | 'AO1_PEEL'
  | 'AO3_INTERPRETATIONS'
  | 'ESSAY_PLAN'
  | 'SYNOPTIC_REVIEW'
  | 'JUDGEMENT_TASK'
  | 'EVIDENCE_BANK'
  | 'SKILLS_FOCUS';

export type PathwayConfig = {
  pathwaySlug: string;
  title: string;
  lessonTitle: string;
  subtitle: string;
  yearGroup: YearGroup;
  courseWeek: number;
  unitNumber: number;
  unitTitle: string;
  mainFocus: string;
  writtenFocus: string;
  writtenFocusType: WrittenFocusType;
  breadthLenses: BreadthLens[];
  status: PathwayStatus;
  routeBase: string;
};

export const PATHWAY_ACTIVITY_ORDER = [
  'lesson_content',
  'flashcards',
  'quiz',
  'peel_response',
  'confidence_exit_ticket',
] as const;

export type PathwayActivityType = typeof PATHWAY_ACTIVITY_ORDER[number];

export const pathwayRegistry: Record<string, PathwayConfig> = {
  'russia-1855': {
    pathwaySlug: 'russia-1855',
    title: 'Russia in 1855',
    lessonTitle: 'Why was Russia difficult to govern in 1855?',
    subtitle: 'Autocracy, geography, social structure, backwardness and serfdom',
    yearGroup: 'Y12',
    courseWeek: 1,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Autocracy, geography, social structure, backwardness and serfdom',
    writtenFocus: 'What made Russia difficult to govern?',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'society', 'economy', 'ideology'],
    status: 'ready',
    routeBase: '/student/lesson/1855',
  },
  'crimean-war': {
    pathwaySlug: 'crimean-war',
    title: 'The Crimean War',
    lessonTitle: 'Why did the Crimean War expose the weaknesses of Tsarist Russia?',
    subtitle: 'Military weakness, administrative problems and pressure for reform',
    yearGroup: 'Y12',
    courseWeek: 2,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Military weakness, administrative problems and pressure for reform',
    writtenFocus: 'Explain why defeat exposed weakness',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'economy', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/crimean-war',
  },
  'power-ideology-control': {
    pathwaySlug: 'power-ideology-control',
    title: 'Power, ideology and control',
    lessonTitle: 'How did autocracy, Orthodoxy and nationality help control Russia?',
    subtitle: 'Autocracy, Orthodoxy, nationality and bureaucracy',
    yearGroup: 'Y12',
    courseWeek: 3,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Autocracy, Orthodoxy, nationality and bureaucracy',
    writtenFocus: 'PEEL: how autocracy worked',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'ideology', 'society'],
    status: 'planned',
    routeBase: '/student/lesson/power-ideology-control',
  },
  'why-serfdom-had-to-end': {
    pathwaySlug: 'why-serfdom-had-to-end',
    title: 'Why serfdom had to end',
    lessonTitle: 'Why did Alexander II decide serfdom had to end?',
    subtitle: 'Economic, social, military and political pressure for emancipation',
    yearGroup: 'Y12',
    courseWeek: 4,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Pressures on Alexander II and the reasons serfdom became unsustainable',
    writtenFocus: 'Causal judgement task',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'economy', 'society', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/why-serfdom-had-to-end',
  },
  'emancipation-serfs': {
    pathwaySlug: 'emancipation-serfs',
    title: 'Emancipation of the serfs',
    lessonTitle: 'How far did emancipation improve the lives of Russian peasants?',
    subtitle: 'Terms of emancipation, gains and losses, redemption payments and the mir',
    yearGroup: 'Y12',
    courseWeek: 5,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Terms of emancipation, gains and losses, redemption payments and the mir',
    writtenFocus: 'PEEL: extent of change',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'economy', 'society', 'individuals'],
    status: 'ready',
    routeBase: '/student/lesson/emancipation-serfs',
  },
  'alexander-ii-wider-reforms': {
    pathwaySlug: 'alexander-ii-wider-reforms',
    title: 'Alexander II’s wider reforms',
    lessonTitle: 'How far did Alexander II modernise Russia through reform?',
    subtitle: 'Zemstva, legal, military, education, censorship and economic reform',
    yearGroup: 'Y12',
    courseWeek: 6,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Zemstva, legal, military, education, censorship and economic reform',
    writtenFocus: 'Reform ranking task',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'economy', 'society', 'individuals'],
    status: 'ready',
    routeBase: '/student/lesson/alexander-ii-wider-reforms',
  },
  'reform-preserve-autocracy': {
    pathwaySlug: 'reform-preserve-autocracy',
    title: 'Reform to preserve autocracy?',
    lessonTitle: 'Did Alexander II reform Russia in order to preserve autocracy?',
    subtitle: 'Limits of reform, motives and continuity of autocratic power',
    yearGroup: 'Y12',
    courseWeek: 7,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Limits of reform, motives and continuity of autocratic power',
    writtenFocus: '25-mark planning task',
    writtenFocusType: 'ESSAY_PLAN',
    breadthLenses: ['governance', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/reform-preserve-autocracy',
  },
  'essay-skills-alexander-ii': {
    pathwaySlug: 'essay-skills-alexander-ii',
    title: 'Essay skills focus: Alexander II',
    lessonTitle: 'How do you build precise AO1 and balanced judgement on Alexander II?',
    subtitle: 'Building precise AO1 and balanced judgement',
    yearGroup: 'Y12',
    courseWeek: 8,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Building precise AO1 and balanced judgement across Alexander II’s reforms',
    writtenFocus: 'Full PEEL paragraph / short essay',
    writtenFocusType: 'SKILLS_FOCUS',
    breadthLenses: ['governance', 'economy', 'society', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/essay-skills-alexander-ii',
  },
  'alexander-ii-reform': {
    pathwaySlug: 'alexander-ii-reform',
    title: 'Alexander II reform overview',
    lessonTitle: 'Why did Alexander II believe Russia needed reform?',
    subtitle: 'Crimean War, serfdom, backwardness and reform from above',
    yearGroup: 'Y12',
    courseWeek: 2,
    unitNumber: 1,
    unitTitle: 'Russia in 1855 and the need for reform',
    mainFocus: 'Bridging overview: Crimean War, serfdom, backwardness and reform from above',
    writtenFocus: 'Explain why reform became necessary',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'economy', 'society', 'individuals'],
    status: 'ready',
    routeBase: '/student/lesson/alexander-ii-reform',
  },
  'later-alexander-ii': {
    pathwaySlug: 'later-alexander-ii',
    title: 'Later Alexander II',
    lessonTitle: 'Why did opposition grow during the later reign of Alexander II?',
    subtitle: 'Reform slowdown, repression after 1866, assassination and populism',
    yearGroup: 'Y12',
    courseWeek: 9,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Reform slowdown, repression after 1866, assassination and populism',
    writtenFocus: 'Turning point judgement',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'opposition', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/later-alexander-ii',
  },
  'alexander-iii-autocracy': {
    pathwaySlug: 'alexander-iii-autocracy',
    title: 'Alexander III and autocracy',
    lessonTitle: 'How far did Alexander III strengthen autocracy?',
    subtitle: 'Personality, political beliefs and reaction after 1881',
    yearGroup: 'Y12',
    courseWeek: 10,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Personality, political beliefs and reaction after 1881',
    writtenFocus: 'Compare Alexander II and Alexander III',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/alexander-iii-autocracy',
  },
  'counter-reform-practice': {
    pathwaySlug: 'counter-reform-practice',
    title: 'Counter-reform in practice',
    lessonTitle: 'How did counter-reform strengthen Tsarist authority?',
    subtitle: 'Land Captains, censorship, education and police powers',
    yearGroup: 'Y12',
    courseWeek: 11,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Land Captains, censorship, education and police powers',
    writtenFocus: 'PEEL: strengthened autocracy?',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'opposition', 'ideology'],
    status: 'planned',
    routeBase: '/student/lesson/counter-reform-practice',
  },
  'russification-minorities': {
    pathwaySlug: 'russification-minorities',
    title: 'Russification and minorities',
    lessonTitle: 'What were the consequences of Russification for the Russian Empire?',
    subtitle: 'Nationalities, Jews, pogroms, Orthodoxy and empire',
    yearGroup: 'Y12',
    courseWeek: 12,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Nationalities, Jews, pogroms, Orthodoxy and empire',
    writtenFocus: 'Explain consequences',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'society', 'ideology', 'opposition'],
    status: 'planned',
    routeBase: '/student/lesson/russification-minorities',
  },
  'ideas-challenged-tsarism': {
    pathwaySlug: 'ideas-challenged-tsarism',
    title: 'Ideas that challenged Tsarism',
    lessonTitle: 'Which ideas challenged Tsarist authority before 1894?',
    subtitle: 'Westernisers, Slavophiles, liberals, populists and socialism',
    yearGroup: 'Y12',
    courseWeek: 13,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Westernisers, Slavophiles, liberals, populists and socialism',
    writtenFocus: 'Ideology sorting task',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['ideology', 'opposition', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/ideas-challenged-tsarism',
  },
  'radical-opposition': {
    pathwaySlug: 'radical-opposition',
    title: 'Radical opposition',
    lessonTitle: 'How effective was radical opposition to Tsarism before 1894?',
    subtitle: 'Populists, Land and Liberty, People’s Will and early Marxism',
    yearGroup: 'Y12',
    courseWeek: 14,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Populists, Land and Liberty, People’s Will and early Marxism',
    writtenFocus: 'Effectiveness of opposition',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['opposition', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/radical-opposition',
  },
  'ao3-reform-reaction-opposition': {
    pathwaySlug: 'ao3-reform-reaction-opposition',
    title: 'AO3 interpretations skills focus',
    lessonTitle: 'How do historians interpret reform, reaction and opposition?',
    subtitle: 'Evaluating historians on reform, reaction and opposition',
    yearGroup: 'Y12',
    courseWeek: 15,
    unitNumber: 2,
    unitTitle: 'Reaction, opposition and Alexander III',
    mainFocus: 'Evaluating historians on reform, reaction and opposition',
    writtenFocus: 'AO3 extract evaluation',
    writtenFocusType: 'AO3_INTERPRETATIONS',
    breadthLenses: ['governance', 'opposition', 'ideology'],
    status: 'planned',
    routeBase: '/student/lesson/ao3-reform-reaction-opposition',
  },
  'industry-before-1894': {
    pathwaySlug: 'industry-before-1894',
    title: 'Industry before 1894',
    lessonTitle: 'How far was Russia industrialising before 1894?',
    subtitle: 'Railways, state-led development and Witte’s early context',
    yearGroup: 'Y12',
    courseWeek: 16,
    unitNumber: 3,
    unitTitle: 'Economy, society and Russia by 1894',
    mainFocus: 'Railways, state-led development and Witte’s early context',
    writtenFocus: 'Economy evidence bank',
    writtenFocusType: 'EVIDENCE_BANK',
    breadthLenses: ['economy', 'society', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/industry-before-1894',
  },
  'agriculture-land-hunger': {
    pathwaySlug: 'agriculture-land-hunger',
    title: 'Agriculture and land hunger',
    lessonTitle: 'Why did rural weakness remain a problem in Russia?',
    subtitle: 'Peasantry, land issue, rural weakness and the mir',
    yearGroup: 'Y12',
    courseWeek: 17,
    unitNumber: 3,
    unitTitle: 'Economy, society and Russia by 1894',
    mainFocus: 'Peasantry, land issue, rural weakness and the mir',
    writtenFocus: 'PEEL: rural weakness',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['economy', 'society', 'governance'],
    status: 'planned',
    routeBase: '/student/lesson/agriculture-land-hunger',
  },
  'social-divisions': {
    pathwaySlug: 'social-divisions',
    title: 'Social divisions',
    lessonTitle: 'How divided was Russian society by 1894?',
    subtitle: 'Nobles, peasants, workers, middle class and intelligentsia',
    yearGroup: 'Y12',
    courseWeek: 18,
    unitNumber: 3,
    unitTitle: 'Economy, society and Russia by 1894',
    mainFocus: 'Nobles, peasants, workers, middle class and intelligentsia',
    writtenFocus: 'Change/continuity judgement',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['society', 'economy', 'opposition'],
    status: 'planned',
    routeBase: '/student/lesson/social-divisions',
  },
  'orthodoxy-culture-authority': {
    pathwaySlug: 'orthodoxy-culture-authority',
    title: 'Orthodoxy, culture and authority',
    lessonTitle: 'How did Orthodoxy and culture support Tsarist authority?',
    subtitle: 'Church, social control, peasant culture and conservatism',
    yearGroup: 'Y12',
    courseWeek: 19,
    unitNumber: 3,
    unitTitle: 'Economy, society and Russia by 1894',
    mainFocus: 'Church, social control, peasant culture and conservatism',
    writtenFocus: 'Explain cultural control',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['society', 'ideology', 'governance'],
    status: 'planned',
    routeBase: '/student/lesson/orthodoxy-culture-authority',
  },
  'tsarism-secure-1894': {
    pathwaySlug: 'tsarism-secure-1894',
    title: 'How secure was Tsarism by 1894?',
    lessonTitle: 'How secure was Tsarism by 1894?',
    subtitle: 'Synoptic review of politics, opposition, economy and society',
    yearGroup: 'Y12',
    courseWeek: 20,
    unitNumber: 3,
    unitTitle: 'Economy, society and Russia by 1894',
    mainFocus: 'Synoptic review: politics, opposition, economy and society',
    writtenFocus: '25-mark plan',
    writtenFocusType: 'ESSAY_PLAN',
    breadthLenses: ['governance', 'opposition', 'economy', 'society', 'ideology'],
    status: 'planned',
    routeBase: '/student/lesson/tsarism-secure-1894',
  },
  'nicholas-ii-ruler': {
    pathwaySlug: 'nicholas-ii-ruler',
    title: 'Nicholas II as ruler',
    lessonTitle: 'How far was Nicholas II responsible for the weakness of autocracy?',
    subtitle: 'Personality, beliefs, weaknesses and comparison with earlier Tsars',
    yearGroup: 'Y12',
    courseWeek: 21,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'Personality, beliefs, weaknesses and comparison with earlier Tsars',
    writtenFocus: 'Character judgement',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'individuals', 'ideology'],
    status: 'planned',
    routeBase: '/student/lesson/nicholas-ii-ruler',
  },
  'industrialisation-nicholas-ii': {
    pathwaySlug: 'industrialisation-nicholas-ii',
    title: 'Industrialisation under Nicholas II',
    lessonTitle: 'What impact did industrialisation have under Nicholas II?',
    subtitle: 'Witte, railways, towns, workers and social tension',
    yearGroup: 'Y12',
    courseWeek: 22,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'Witte, railways, towns, workers and social tension',
    writtenFocus: 'Explain impact of industrialisation',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['economy', 'society', 'opposition', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/industrialisation-nicholas-ii',
  },
  'opposition-before-1905': {
    pathwaySlug: 'opposition-before-1905',
    title: 'Opposition before 1905',
    lessonTitle: 'How serious was opposition to Tsarism before 1905?',
    subtitle: 'Liberals, SRs, SDs, Marxism, Lenin and workers',
    yearGroup: 'Y12',
    courseWeek: 23,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'Liberals, SRs, SDs, Marxism, Lenin and workers',
    writtenFocus: 'Opposition effectiveness grid',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['opposition', 'ideology', 'society', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/opposition-before-1905',
  },
  '1905-revolution': {
    pathwaySlug: '1905-revolution',
    title: 'The 1905 Revolution',
    lessonTitle: 'Was the 1905 Revolution a turning point for Tsarist Russia?',
    subtitle: 'War, Bloody Sunday, strikes, soviets and the October Manifesto',
    yearGroup: 'Y12',
    courseWeek: 24,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'War, Bloody Sunday, strikes, soviets and the October Manifesto',
    writtenFocus: 'Current pilot pathway',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'opposition', 'economy', 'society', 'individuals'],
    status: 'ready',
    routeBase: '/student/lesson/1905',
  },
  'manifesto-fundamental-laws': {
    pathwaySlug: 'manifesto-fundamental-laws',
    title: 'From Manifesto to Fundamental Laws',
    lessonTitle: 'Did the October Manifesto and Fundamental Laws really limit autocracy?',
    subtitle: 'Duma, Fundamental Laws and limits of constitutionalism',
    yearGroup: 'Y12',
    courseWeek: 25,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'Duma, Fundamental Laws and limits of constitutionalism',
    writtenFocus: 'PEEL: did autocracy survive?',
    writtenFocusType: 'AO1_PEEL',
    breadthLenses: ['governance', 'opposition', 'ideology'],
    status: 'planned',
    routeBase: '/student/lesson/manifesto-fundamental-laws',
  },
  'stolypin-reform': {
    pathwaySlug: 'stolypin-reform',
    title: 'Stolypin and reform',
    lessonTitle: 'How successful was Stolypin in strengthening Tsarism?',
    subtitle: 'Repression, land reform, Dumas and the wager on the strong',
    yearGroup: 'Y12',
    courseWeek: 26,
    unitNumber: 4,
    unitTitle: 'Nicholas II and the road to 1905',
    mainFocus: 'Repression, land reform, Dumas and the wager on the strong',
    writtenFocus: 'Success/failure judgement',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'economy', 'society', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/stolypin-reform',
  },
  'russia-before-1914': {
    pathwaySlug: 'russia-before-1914',
    title: 'Russia before 1914',
    lessonTitle: 'How stable was Tsarism before 1914?',
    subtitle: 'Economy, society, opposition and politics before war',
    yearGroup: 'Y12',
    courseWeek: 27,
    unitNumber: 5,
    unitTitle: 'War, collapse and revolution in 1917',
    mainFocus: 'How stable was Tsarism? Economy, society, opposition and politics',
    writtenFocus: 'Synoptic judgement',
    writtenFocusType: 'SYNOPTIC_REVIEW',
    breadthLenses: ['governance', 'opposition', 'economy', 'society'],
    status: 'planned',
    routeBase: '/student/lesson/russia-before-1914',
  },
  'russia-first-world-war': {
    pathwaySlug: 'russia-first-world-war',
    title: 'Russia and the First World War',
    lessonTitle: 'How did the First World War weaken Tsarism?',
    subtitle: 'Military, economic, social and political impact of war',
    yearGroup: 'Y12',
    courseWeek: 28,
    unitNumber: 5,
    unitTitle: 'War, collapse and revolution in 1917',
    mainFocus: 'Military, economic, social and political impact of war',
    writtenFocus: 'Cause/consequence task',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'economy', 'society', 'opposition', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/russia-first-world-war',
  },
  'february-revolution': {
    pathwaySlug: 'february-revolution',
    title: 'February Revolution',
    lessonTitle: 'Why did the February Revolution bring down Tsarism?',
    subtitle: 'Petrograd, workers, women, soldiers, Duma and abdication',
    yearGroup: 'Y12',
    courseWeek: 29,
    unitNumber: 5,
    unitTitle: 'War, collapse and revolution in 1917',
    mainFocus: 'Petrograd, workers, women, soldiers, Duma and abdication',
    writtenFocus: 'Causal ranking',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'opposition', 'society', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/february-revolution',
  },
  'feb-oct-1917': {
    pathwaySlug: 'feb-oct-1917',
    title: 'From February to October',
    lessonTitle: 'Why did the Provisional Government collapse in 1917?',
    subtitle: 'Provisional Government, dual power, Lenin, Bolsheviks and October',
    yearGroup: 'Y12',
    courseWeek: 30,
    unitNumber: 5,
    unitTitle: 'War, collapse and revolution in 1917',
    mainFocus: 'Provisional Government, dual power, Lenin, Bolsheviks and October',
    writtenFocus: '25-mark essay plan/model',
    writtenFocusType: 'ESSAY_PLAN',
    breadthLenses: ['governance', 'opposition', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/feb-oct-1917',
  },
  'lenin-ideology-change': {
    pathwaySlug: 'lenin-ideology-change',
    title: 'Lenin’s Russia: ideology and change',
    lessonTitle: 'How far was Lenin’s Russia shaped by ideology?',
    subtitle: 'Marxism, Leninism, Sovnarkom, decrees and one-party rule',
    yearGroup: 'Y13',
    courseWeek: 1,
    unitNumber: 6,
    unitTitle: 'Lenin and the emergence of Communist dictatorship',
    mainFocus: 'Marxism, Leninism, Sovnarkom, decrees and one-party rule',
    writtenFocus: 'Ideology vs pragmatism',
    writtenFocusType: 'JUDGEMENT_TASK',
    breadthLenses: ['governance', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/lenin-ideology-change',
  },
  'stalin-postwar-khrushchev': {
    pathwaySlug: 'stalin-postwar-khrushchev',
    title: 'Stalin and Khrushchev, 1945–64',
    lessonTitle: 'How far did Stalin and Khrushchev transform the USSR after 1945?',
    subtitle: 'Recovery, reform, repression and de-Stalinisation',
    yearGroup: 'Y13',
    courseWeek: 30,
    unitNumber: 10,
    unitTitle: 'Khrushchev, reform and reaction, 1953–1964',
    mainFocus: 'Recovery, reform, repression and de-Stalinisation',
    writtenFocus: 'AO3/25-mark plan',
    writtenFocusType: 'ESSAY_PLAN',
    breadthLenses: ['governance', 'economy', 'society', 'ideology', 'individuals'],
    status: 'planned',
    routeBase: '/student/lesson/stalin-postwar-khrushchev',
  },
};

export const pathwayOptions = Object.values(pathwayRegistry).sort((first, second) => {
  if (first.yearGroup !== second.yearGroup) return first.yearGroup.localeCompare(second.yearGroup);
  return first.courseWeek - second.courseWeek;
});

export function getPathwayConfig(pathwaySlug: string | null | undefined) {
  if (pathwaySlug && pathwayRegistry[pathwaySlug]) return pathwayRegistry[pathwaySlug];
  return pathwayRegistry['1905-revolution'];
}

export function getActivityRoute(routeBase: string, activityType: string) {
  const suffixByType: Record<string, string> = {
    lesson_content: 'lesson',
    flashcards: 'flashcards',
    quiz: 'quiz',
    peel_response: 'peel',
    confidence_exit_ticket: 'confidence',
  };

  return `${routeBase}/${suffixByType[activityType] ?? ''}`;
}

export function orderActivityTypes(activityTypes: string[]) {
  return [...activityTypes].sort((first, second) => {
    const firstIndex = PATHWAY_ACTIVITY_ORDER.indexOf(first as PathwayActivityType);
    const secondIndex = PATHWAY_ACTIVITY_ORDER.indexOf(second as PathwayActivityType);
    const safeFirstIndex = firstIndex === -1 ? 999 : firstIndex;
    const safeSecondIndex = secondIndex === -1 ? 999 : secondIndex;
    return safeFirstIndex - safeSecondIndex;
  });
}
