export const industrialisationNicholasIIPathwaySlug='industrialisation-nicholas-ii';
export const industrialisationNicholasIILessonSections=[
{heading:'The industrial drive',body:'Under Nicholas II the state accelerated industrial growth through tariffs, foreign loans, railway building and support for heavy industry. Witte believed economic modernisation would strengthen the state and preserve autocracy.',question:'Why did the state promote industry?',taskType:'explain'},
{heading:'Witte',body:'As Finance Minister from 1892 to 1903, Sergei Witte coordinated railway expansion, foreign borrowing and the gold standard. His programme prioritised national power over immediate living standards.',question:'How important was Witte personally?',taskType:'judgement'},
{heading:'Railways',body:'The Trans-Siberian Railway and wider network linked markets, moved grain and coal, and supported military mobilisation. Railway expansion also stimulated iron, steel and engineering.',question:'Why were railways a multiplier of growth?',taskType:'explain'},
{heading:'Foreign capital',body:'French, Belgian and British investment supplied capital and technology unavailable domestically. This accelerated growth but increased dependence on overseas confidence and debt.',question:'Was foreign investment a strength or weakness?',taskType:'comparison'},
{heading:'Heavy industry',body:'Coal, iron, steel and oil output rose sharply, especially in the Donbas, Ukraine, Poland, the Urals and Baku. Growth remained concentrated in a few regions.',question:'Why does regional concentration matter?',taskType:'judgement'},
{heading:'Urbanisation',body:'Rapid migration created expanding cities such as St Petersburg and Moscow. Housing, sanitation and food supply failed to keep pace.',question:'How did urban growth create instability?',taskType:'explain'},
{heading:'The workforce',body:'Industrial workers endured long hours, low wages, fines and dangerous conditions. Concentration in large factories made collective protest easier than among dispersed peasants.',question:'Why could a small working class be politically significant?',taskType:'judgement'},
{heading:'Labour unrest',body:'Strikes increased in the late 1890s and early 1900s. The state alternated between police repression and limited factory regulation, while revolutionary parties targeted workers.',question:'How did industrialisation strengthen opposition?',taskType:'explain'},
{heading:'Costs to the countryside',body:'High indirect taxes and grain exports helped finance the state. Peasants bore much of the burden, linking industrial advance to rural hardship.',question:'Did industrialisation weaken agriculture?',taskType:'comparison'},
{heading:'Overall impact',body:'Industrialisation increased revenue, military capacity and infrastructure, but produced uneven growth, urban hardship and a more organised workforce. It strengthened the state materially while widening social tension.',question:'What was the overall impact by 1905?',taskType:'judgement'}];
export const industrialisationNicholasIITimeline={events:[{id:'1891',date:'1891',title:'Trans-Siberian Railway begun',detail:'The state commits to a vast transport project.'},{id:'1892',date:'1892',title:'Witte becomes Finance Minister',detail:'Economic policy gains stronger central direction.'},{id:'1894',date:'1894',title:'Nicholas II succeeds',detail:'Industrial expansion continues under the new Tsar.'},{id:'1897',date:'1897',title:'Gold standard',detail:'The rouble becomes more attractive to foreign investors.'},{id:'1897l',date:'1897',title:'Factory law',detail:'The working day is limited, though enforcement remains weak.'},{id:'1899',date:'1899',title:'Industrial boom peaks',detail:'Heavy industry and foreign investment expand rapidly.'},{id:'1901',date:'1901',title:'Obukhov strike',detail:'Labour militancy becomes more visible.'},{id:'1903',date:'1903',title:'Witte removed from Finance Ministry',detail:'Court opposition limits his influence.'},{id:'1905',date:'1905',title:'Mass strikes',detail:'Industrial workers become central to revolution.'}]};
export const industrialisationNicholasIIFlashcards=[{id:'witte',front:'Sergei Witte',back:'Finance Minister who drove state-led industrialisation.'},{id:'gold',front:'Gold standard',back:'A currency system that increased investor confidence.'},{id:'tariffs',front:'Protective tariffs',back:'Taxes on imports used to shield Russian industry.'},{id:'foreign',front:'Foreign capital',back:'Overseas investment, especially from France and Belgium.'},{id:'railways',front:'Trans-Siberian Railway',back:'Major railway linking European Russia with Siberia and the Pacific.'},{id:'heavy',front:'Heavy industry',back:'Coal, iron, steel, oil and engineering.'},{id:'urbanisation',front:'Urbanisation',back:'Growth of towns as migrants moved into industrial work.'},{id:'proletariat',front:'Proletariat',back:'Industrial wage-earning working class.'},{id:'concentration',front:'Worker concentration',back:'Large numbers employed together in major factories.'},{id:'taxation',front:'Indirect taxation',back:'Taxes on goods that fell heavily on poorer consumers.'},{id:'uneven',front:'Uneven development',back:'Rapid growth in selected sectors and regions alongside broad backwardness.'},{id:'autocracy',front:'Economic modernisation',back:'State-led development intended to strengthen rather than democratise Russia.'}];
export const industrialisationNicholasIIQuiz=[{id:'q1',question:'Who directed industrial policy?',options:['Witte','Stolypin','Gapon','Rasputin'],correct:'Witte'},{id:'q2',question:'What major railway began in 1891?',options:['Trans-Siberian','Baikal-Amur','Moscow Metro','Warsaw Express'],correct:'Trans-Siberian'},{id:'q3',question:'What did the gold standard encourage?',options:['Foreign investment','Peasant land redistribution','Trade union freedom','Universal suffrage'],correct:'Foreign investment'},{id:'q4',question:'Which sector grew fastest?',options:['Heavy industry','Subsistence farming','Domestic service','Hand spinning'],correct:'Heavy industry'},{id:'q5',question:'Why were large factories politically important?',options:['Workers could organise collectively','They isolated workers','They ended strikes','They weakened cities'],correct:'Workers could organise collectively'},{id:'q6',question:'What burden helped finance growth?',options:['Indirect taxes','Income tax on nobles only','Duma taxation','Church tithes'],correct:'Indirect taxes'},{id:'q7',question:'Where was growth concentrated?',options:['A few major regions','Every village equally','Only Siberian farms','Only Finland'],correct:'A few major regions'},{id:'q8',question:'What social process accompanied industrial growth?',options:['Urbanisation','De-urbanisation','Universal land ownership','Rural depopulation without cities'],correct:'Urbanisation'},{id:'q9',question:'What was one state benefit?',options:['Greater revenue and military capacity','Immediate democracy','End of foreign debt','Abolition of poverty'],correct:'Greater revenue and military capacity'},{id:'q10',question:'Which judgement is strongest?',options:['Industrialisation strengthened state power but intensified social tension','It had only positive effects','It ended opposition','It transformed all Russia equally'],correct:'Industrialisation strengthened state power but intensified social tension'}];
export const industrialisationNicholasIIJudgement={question:'Rank the consequences of industrialisation by importance for Tsarism.',factors:[{id:'revenue',title:'State revenue',detail:'Industry and trade enlarged the tax base.'},{id:'military',title:'Military capacity',detail:'Railways and heavy industry supported mobilisation.'},{id:'foreign',title:'Foreign dependence',detail:'Growth relied heavily on overseas loans.'},{id:'workers',title:'Worker militancy',detail:'Factory concentration encouraged strikes.'},{id:'cities',title:'Urban hardship',detail:'Housing and sanitation lagged behind.'},{id:'rural',title:'Rural burden',detail:'Taxes and grain exports increased peasant pressure.'}]};
export const industrialisationNicholasIIAO3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Witte’s programme created the material foundations of a modern great power.'},{historian:'Interpretation B',argument:'Industrialisation was dangerously unbalanced because the peasantry financed growth and workers gained little.'},{historian:'Interpretation C',argument:'The most important effect was political: industrial growth concentrated workers and made mass protest possible.'}]};
export const industrialisationNicholasIIPeel={question:'“Industrialisation strengthened Tsarism in the years 1894 to 1905.” Assess the validity of this view.',stretchQuestion:'Plan a thematic essay balancing economic power against social and political costs.',scaffold:['Define strength.','Use Witte, railways and heavy industry as precise evidence.','Assess foreign capital and uneven growth.','Explain the impact on workers and peasants.','Reach a balanced overall judgement.']};
export const industrialisationNicholasIIConfidence={prompt:'How confident are you explaining industrialisation under Nicholas II?',leastSecureOptions:['Witte','Railways','Foreign capital','Heavy industry','Workers','Peasants','Overall impact'],scale:[1,2,3,4,5]};
export const industrialisationNicholasIIFallbacks:Record<string,any>={lesson_content:{sections:industrialisationNicholasIILessonSections},timeline:industrialisationNicholasIITimeline,flashcards:{cards:industrialisationNicholasIIFlashcards},quiz:{questions:industrialisationNicholasIIQuiz},judgement_ranking:industrialisationNicholasIIJudgement,ao3_interpretation:industrialisationNicholasIIAO3,peel_response:industrialisationNicholasIIPeel,confidence_exit_ticket:industrialisationNicholasIIConfidence};