export const pathway1905LessonSections = [
  {
    heading: 'The enquiry',
    body: 'Was the 1905 Revolution a turning point for Tsarist Russia? The answer is balanced. It exposed the weakness of autocracy and forced Nicholas II to make concessions, but it did not destroy Tsarist power. The regime survived by combining reform, repression and the loyalty of the army.',
    question: 'In one sentence, explain the balanced judgement about whether 1905 was a turning point.',
    taskType: 'judgement',
    teacherNote: 'Look for a balanced judgement: change/weakening, but survival of Tsarist authority.',
    media: {
      type: 'video',
      title: 'Test video: Russia exam walkthrough',
      url: 'https://www.youtube.com/watch?v=57AxyoGigXo',
      caption: 'Test embedded video panel. Watch enough to check that the embed loads and sits cleanly inside the lesson screen.',
      credit: 'YouTube embed test.',
    },
  },
  {
    heading: 'Long-term weaknesses in Tsarist authority',
    body: 'By 1905, the Russian Empire was still an autocracy with limited political representation. Rapid industrial growth had created urban workers who faced poor conditions, long hours and low wages. Peasants remained frustrated by land hunger and redemption payments. These pressures meant that defeat or crisis could quickly become political opposition.',
    question: 'Identify one long-term weakness and explain why it made Tsarist authority vulnerable.',
    taskType: 'explain',
  },
  {
    heading: 'The Russo-Japanese War, 1904–05',
    body: 'War with Japan exposed the weaknesses of the Tsarist state. Russia suffered humiliating defeats, including the destruction of the Baltic Fleet at Tsushima in May 1905. The war damaged the prestige of Nicholas II and made it easier for critics to argue that autocracy was incompetent as well as unfair.',
    question: 'How did defeat in the Russo-Japanese War weaken Nicholas II’s authority?',
    taskType: 'explain',
  },
  {
    heading: 'Bloody Sunday',
    body: 'On 9 January 1905, Father Gapon led peaceful workers to the Winter Palace to present a petition. Troops fired on the crowd. This shattered the image of the Tsar as the protective Little Father and turned economic frustration into a wider political crisis.',
    question: 'Use the source to explain why Bloody Sunday damaged the Tsar’s image as the Little Father.',
    taskType: 'source_inference',
    media: {
      type: 'source',
      title: 'Bloody Sunday petition, January 1905',
      sourceText: '“Sire, we workers, our wives and our children have come to you seeking truth and protection. We are impoverished, oppressed and overburdened with labour.”',
      caption: 'This short extract captures the loyal, petitioning tone of many marchers before troops opened fire.',
      credit: 'Adapted classroom extract.',
    },
  },
  {
    heading: 'Spread of unrest',
    body: 'After Bloody Sunday, strikes, peasant disturbances, national minority protests and army/navy mutinies spread across the empire. The Potemkin mutiny in June 1905 showed that loyalty within the armed forces could not be taken for granted, although most of the army remained loyal enough to save the regime.',
    question: 'Give one example of unrest after Bloody Sunday and explain what it showed about the regime’s authority.',
    taskType: 'explain',
  },
  {
    heading: 'The St Petersburg Soviet',
    body: 'The St Petersburg Soviet emerged during the October general strike as a workers’ council coordinating action. It gave opposition a more organised form and showed that new revolutionary institutions could challenge state authority in the cities.',
    question: 'Why was the St Petersburg Soviet a more serious challenge than ordinary protest?',
    taskType: 'explain',
  },
  {
    heading: 'The October Manifesto',
    body: 'Nicholas II issued the October Manifesto in 1905. It promised civil liberties and an elected Duma. This divided the opposition because liberals were partly satisfied, while radicals wanted deeper change. The manifesto was a tactical concession that helped the regime survive.',
    question: 'Explain how the October Manifesto helped the regime survive, even though it looked like a concession.',
    taskType: 'explain',
    media: {
      type: 'source',
      title: 'October Manifesto, 1905',
      sourceText: '“The population shall be granted the immutable foundations of civic freedom based on the real inviolability of person, freedom of conscience, speech, assembly and association.”',
      caption: 'The promise of civil liberties helped split moderate liberals from more radical opponents.',
      credit: 'Adapted classroom extract.',
    },
  },
  {
    heading: 'Why the regime survived',
    body: 'The Tsarist regime survived because opposition groups were divided, the army largely remained loyal, and Witte used concessions to split moderates from revolutionaries. Repression then followed. This means 1905 weakened autocracy, but it was not a full revolution because the Tsar retained control.',
    question: 'What was the most important reason the Tsarist regime survived 1905? Give a brief judgement.',
    taskType: 'judgement',
  },
];

export const pathway1905QuizQuestions = [
  {
    id: 'bloody-sunday-date',
    question: 'When did Bloody Sunday take place?',
    options: ['January 1905', 'June 1905', 'October 1905', 'April 1906'],
    correct: 'January 1905',
  },
  {
    id: 'father-gapon',
    question: 'Who led the workers’ petition to the Winter Palace on Bloody Sunday?',
    options: ['Lenin', 'Trotsky', 'Father Gapon', 'Sergei Witte'],
    correct: 'Father Gapon',
  },
  {
    id: 'little-father',
    question: 'What image of the Tsar was damaged by Bloody Sunday?',
    options: ['The Red Tsar', 'Little Father', 'Iron Chancellor', 'Father of the Duma'],
    correct: 'Little Father',
  },
  {
    id: 'russo-japanese-war',
    question: 'Which war exposed the weakness of the Tsarist regime in 1904–05?',
    options: ['Crimean War', 'First World War', 'Russo-Japanese War', 'Civil War'],
    correct: 'Russo-Japanese War',
  },
  {
    id: 'tsushima',
    question: 'Which naval defeat humiliated Russia during the Russo-Japanese War?',
    options: ['Tsushima', 'Sevastopol', 'Kronstadt', 'Borodino'],
    correct: 'Tsushima',
  },
  {
    id: 'long-term-weakness-workers',
    question: 'Which long-term pressure helped make urban workers receptive to protest by 1905?',
    options: ['High wages and short hours', 'Poor conditions and low wages', 'Full trade union rights', 'Guaranteed political representation'],
    correct: 'Poor conditions and low wages',
  },
  {
    id: 'peasant-pressure',
    question: 'Which issue helps explain continuing peasant unrest before and during 1905?',
    options: ['Land hunger', 'Collectivisation', 'The New Economic Policy', 'Dekulakisation'],
    correct: 'Land hunger',
  },
  {
    id: 'potemkin',
    question: 'What did the Potemkin mutiny reveal in 1905?',
    options: ['Peasant loyalty was total', 'The Duma had real power', 'Military loyalty could be fragile', 'The Tsar had abdicated'],
    correct: 'Military loyalty could be fragile',
  },
  {
    id: 'october-strike',
    question: 'Which event placed the regime under intense pressure in October 1905?',
    options: ['A general strike', 'The Treaty of Brest-Litovsk', 'The Kornilov Affair', 'The July Days'],
    correct: 'A general strike',
  },
  {
    id: 'st-petersburg-soviet-role',
    question: 'Why was the St Petersburg Soviet significant?',
    options: ['It was a royal advisory council', 'It coordinated worker action and showed organised urban opposition', 'It gave the Tsar absolute power', 'It ended the Russo-Japanese War'],
    correct: 'It coordinated worker action and showed organised urban opposition',
  },
  {
    id: 'october-manifesto',
    question: 'What did the October Manifesto promise?',
    options: ['Immediate abdication', 'Civil liberties and an elected Duma', 'Collectivisation', 'Peace, land and bread'],
    correct: 'Civil liberties and an elected Duma',
  },
  {
    id: 'october-manifesto-impact',
    question: 'How did the October Manifesto help the regime survive?',
    options: ['It united all opposition groups', 'It split moderates from radicals', 'It abolished the Tsar', 'It transferred power to the Soviet'],
    correct: 'It split moderates from radicals',
  },
  {
    id: 'duma',
    question: 'What was the Duma?',
    options: ['A workers’ militia', 'An elected legislative assembly', 'A secret police unit', 'A peasant commune'],
    correct: 'An elected legislative assembly',
  },
  {
    id: 'witte-role',
    question: 'What was Sergei Witte’s significance in 1905?',
    options: ['He led the Bolshevik seizure of power', 'He advised concessions that helped stabilise the regime', 'He commanded the Potemkin mutiny', 'He abolished the Okhrana'],
    correct: 'He advised concessions that helped stabilise the regime',
  },
  {
    id: 'army-loyalty',
    question: 'Why was army loyalty crucial to the survival of Tsarism in 1905?',
    options: ['It allowed the regime to repress unrest once opposition divided', 'It gave workers control of Petrograd', 'It forced Nicholas II to abdicate', 'It made the Duma fully democratic'],
    correct: 'It allowed the regime to repress unrest once opposition divided',
  },
  {
    id: 'survival-factor',
    question: 'Which factor most helped the Tsarist regime survive 1905?',
    options: ['United opposition', 'Complete military collapse', 'Divided opposition and army loyalty', 'Immediate land reform'],
    correct: 'Divided opposition and army loyalty',
  },
  {
    id: 'turning-point-judgement',
    question: 'Which judgement best fits the significance of 1905?',
    options: ['It had no impact', 'It weakened autocracy but did not destroy it', 'It created communist rule', 'It ended the Romanov dynasty immediately'],
    correct: 'It weakened autocracy but did not destroy it',
  },
  {
    id: 'best-evidence-weakening',
    question: 'Which evidence best supports the argument that 1905 weakened Tsarist authority?',
    options: ['The Tsar was forced to issue the October Manifesto', 'The Tsar introduced collectivisation', 'The Bolsheviks won a majority in the Duma', 'Russia won the Russo-Japanese War'],
    correct: 'The Tsar was forced to issue the October Manifesto',
  },
];

export const pathway1905Flashcards = [
  { id: 'bloody-sunday', front: 'Bloody Sunday', back: '9 January 1905: peaceful protesters were shot by troops, damaging the Tsar’s image as Little Father.' },
  { id: 'father-gapon', front: 'Father Gapon', back: 'Priest who led the workers’ petition to the Winter Palace. His role shows many protesters still appealed to the Tsar rather than initially seeking revolution.' },
  { id: 'little-father', front: 'Little Father', back: 'Traditional image of the Tsar as a protective paternal ruler. Bloody Sunday badly damaged this image.' },
  { id: 'russo-japanese-war', front: 'Russo-Japanese War', back: '1904–05 conflict that exposed Russian military and administrative weakness, especially after defeat at Tsushima.' },
  { id: 'tsushima', front: 'Tsushima', back: 'May 1905 naval disaster where the Russian Baltic Fleet was destroyed by Japan, humiliating the regime.' },
  { id: 'industrial-workers', front: 'Urban worker grievances', back: 'Poor conditions, long hours, low wages and overcrowded cities helped make workers receptive to strikes and protest.' },
  { id: 'peasant-land-hunger', front: 'Peasant land hunger', back: 'Peasants wanted more land and remained frustrated by poverty and obligations, making rural unrest a serious pressure on the regime.' },
  { id: 'october-general-strike', front: 'October General Strike', back: 'A major strike wave that paralysed parts of the empire and forced Nicholas II to issue the October Manifesto.' },
  { id: 'october-manifesto', front: 'October Manifesto', back: 'Concession promising civil liberties and an elected Duma; it split moderates from radicals and helped the regime survive.' },
  { id: 'duma', front: 'Duma', back: 'Elected assembly promised in 1905. It looked like constitutional reform, but the Tsar later limited its power.' },
  { id: 'st-petersburg-soviet', front: 'St Petersburg Soviet', back: 'Workers’ council that coordinated action in 1905 and showed a new form of organised urban opposition.' },
  { id: 'soviet-significance', front: 'Why the St Petersburg Soviet mattered', back: 'It showed that opposition could become organised and coordinated, not just spontaneous protest.' },
  { id: 'potemkin-mutiny', front: 'Potemkin mutiny', back: 'June 1905 naval mutiny showing some discontent within the armed forces, although the wider army remained loyal enough to protect the regime.' },
  { id: 'army-loyalty', front: 'Army loyalty', back: 'Most of the army remained loyal. This was crucial because the regime could repress unrest once moderate opposition had been split.' },
  { id: 'witte', front: 'Sergei Witte', back: 'Tsarist minister who helped advise concessions in 1905. His strategy helped divide opposition and stabilise the regime.' },
  { id: 'divided-opposition', front: 'Divided opposition', back: 'Liberals, workers, peasants and revolutionaries wanted different outcomes, making it harder to overthrow the regime.' },
  { id: 'liberals', front: 'Liberals in 1905', back: 'Many liberals wanted constitutional reform rather than full revolution, so the October Manifesto partly satisfied and divided them.' },
  { id: 'radicals', front: 'Radicals in 1905', back: 'Socialists and revolutionary groups wanted more fundamental change, but they lacked enough unity and force to remove the regime in 1905.' },
  { id: 'reform-and-repression', front: 'Reform and repression', back: 'The regime survived by making tactical concessions, then using force once opposition had been divided.' },
  { id: 'limited-turning-point', front: 'Limited turning point', back: '1905 forced concessions and exposed weakness, but autocracy survived and Nicholas II retained significant power.' },
  { id: 'evidence-weakening', front: 'Evidence that 1905 weakened autocracy', back: 'Bloody Sunday damaged legitimacy, the general strike forced concessions, and the Soviet showed organised opposition.' },
  { id: 'evidence-survival', front: 'Evidence that 1905 was limited', back: 'The Tsar survived, opposition divided, the army largely stayed loyal and the Duma’s power was later restricted.' },
  { id: 'causal-chain', front: 'Causal chain: war to concession', back: 'Defeat in war weakened prestige; Bloody Sunday triggered protest; strikes paralysed the state; the October Manifesto offered concessions.' },
  { id: 'essay-judgement', front: 'Best judgement line', back: 'The 1905 Revolution significantly weakened Tsarist authority by exposing autocratic vulnerability, but it was limited because the regime survived through concessions, repression and army loyalty.' },
];

export const pathway1905PeelContent = {
  question: 'Explain one way in which the 1905 Revolution weakened Tsarist authority.',
  stretchQuestion: 'How significant was the 1905 Revolution in weakening Tsarist authority?',
  scaffold: [
    'Point: identify one clear way the revolution weakened authority, such as loss of legitimacy, forced concessions, or organised opposition.',
    'Evidence: use precise evidence such as Bloody Sunday, the October General Strike, the St Petersburg Soviet, or the October Manifesto.',
    'Explain: show how this reduced trust in autocracy or forced Nicholas II to retreat.',
    'Link: judge whether this was a serious or limited weakening of Tsarist authority.',
  ],
};
