export const februaryRevolutionPathwaySlug='february-revolution';
export const februaryRevolutionLessonSections=[
{heading:'The enquiry',body:'The February Revolution brought down a three-hundred-year dynasty in days. The key issue is why economic protest became political revolution and why the army ceased to defend the regime.',question:'Why did the February Revolution succeed?',taskType:'judgement'},
{heading:'Petrograd in crisis',body:'By early 1917 Petrograd faced bread shortages, fuel problems, inflation and bitter winter conditions. Queues and factory unrest created a volatile urban environment.',question:'Why did hardship become revolutionary?',taskType:'explain'},
{heading:'Women and protest',body:'On International Women’s Day, women textile workers marched for bread and called other workers out. Their action helped turn scattered grievances into a mass strike.',question:'How significant were women in beginning the revolution?',taskType:'judgement'},
{heading:'General strike',body:'Demonstrations expanded as factories closed and crowds demanded bread, peace and an end to Tsarism. The movement became political because the government could not restore order.',question:'When did protest become revolution?',taskType:'judgement'},
{heading:'Army mutiny',body:'Troops ordered to fire on crowds increasingly refused, mutinied and joined demonstrators. Once the Petrograd garrison defected, the regime lost the coercive force needed to survive.',question:'Why was mutiny decisive?',taskType:'judgement'},
{heading:'The Duma',body:'Nicholas ordered the Duma dissolved, but leading deputies formed a Temporary Committee. This created an alternative centre of political authority as the old government collapsed.',question:'How important was elite action?',taskType:'judgement'},
{heading:'The Petrograd Soviet',body:'Workers and soldiers formed the Petrograd Soviet. Order Number 1 asserted influence over the garrison and ensured that military obedience depended on Soviet approval.',question:'What did the Soviet reveal about power?',taskType:'explain'},
{heading:'Nicholas II',body:'Nicholas was away at headquarters, received poor advice and failed to grasp the scale of the crisis. Railway disruption prevented his return and senior generals advised abdication.',question:'How far did Nicholas cause his own downfall?',taskType:'judgement'},
{heading:'Abdication',body:'Nicholas abdicated on 2 March 1917. His brother Michael declined the throne without approval from a constituent assembly, ending Romanov rule.',question:'Why did the monarchy collapse so quickly?',taskType:'judgement'},
{heading:'Overall judgement',body:'The revolution succeeded because long-term weakness and wartime hardship combined with immediate protest, army mutiny and elite abandonment. The decisive turning point was the loss of military support.',question:'Why did February bring down Tsarism?',taskType:'judgement'}];
export const februaryRevolutionTimeline={events:[{id:'23feb',date:'23 February 1917',title:'Women’s demonstrations',detail:'Bread protests begin on International Women’s Day.'},{id:'24feb',date:'24–25 February',title:'Mass strikes',detail:'Industrial action and demonstrations spread across Petrograd.'},{id:'26feb',date:'26 February',title:'Troops ordered to fire',detail:'Some units shoot protesters but discipline starts to collapse.'},{id:'27feb',date:'27 February',title:'Garrison mutiny',detail:'Soldiers join crowds and seize weapons.'},{id:'27feb2',date:'27 February',title:'Duma Committee and Soviet',detail:'Two new centres of authority emerge.'},{id:'2mar',date:'2 March 1917',title:'Nicholas abdicates',detail:'Romanov rule ends.'}]};
export const februaryRevolutionFlashcards=[{id:'iwd',front:'International Women’s Day',back:'23 February 1917, when women textile workers began mass bread protests.'},{id:'garrison',front:'Petrograd garrison',back:'Troops stationed in the capital whose mutiny destroyed the regime’s control.'},{id:'mutiny',front:'Mutiny',back:'Soldiers refusing orders and turning against commanders.'},{id:'committee',front:'Temporary Committee',back:'Duma deputies who formed an alternative authority.'},{id:'soviet',front:'Petrograd Soviet',back:'Council of workers’ and soldiers’ deputies formed during the revolution.'},{id:'order1',front:'Order Number 1',back:'Soviet order asserting influence over soldiers and the garrison.'},{id:'abdication',front:'Abdication',back:'Nicholas II’s surrender of the throne on 2 March 1917.'},{id:'dual',front:'Dual power',back:'The coexistence of the Provisional Government and Petrograd Soviet.'},{id:'bread',front:'Bread queues',back:'A visible symbol of urban supply crisis and government failure.'},{id:'coercion',front:'Loss of coercion',back:'The state’s inability to command troops to suppress protest.'},{id:'elite',front:'Elite abandonment',back:'Generals and politicians withdrawing support from Nicholas.'},{id:'spontaneous',front:'Spontaneous revolution',back:'A revolution not directed at first by a single central party.'}];
export const februaryRevolutionQuiz=[{id:'q1',question:'Who helped begin the protests on 23 February?',options:['Women textile workers','The army high command','The Kadet ministers','The Constituent Assembly'],correct:'Women textile workers'},{id:'q2',question:'What immediate issue drove many demonstrators?',options:['Bread shortages','Collectivisation','NEP taxes','The Treaty of Brest-Litovsk'],correct:'Bread shortages'},{id:'q3',question:'What made the revolution decisive?',options:['The garrison mutiny','A German invasion of Petrograd','The October Manifesto','A peasant election'],correct:'The garrison mutiny'},{id:'q4',question:'What did Duma deputies form?',options:['Temporary Committee','Cheka','Sovnarkom','Politburo'],correct:'Temporary Committee'},{id:'q5',question:'What new workers’ and soldiers’ body emerged?',options:['Petrograd Soviet','Third Duma','Zemstvo Union','Council of Ministers'],correct:'Petrograd Soviet'},{id:'q6',question:'What did Order Number 1 concern?',options:['Soldiers and military obedience','Land redistribution','Factory nationalisation','Peace with Germany'],correct:'Soldiers and military obedience'},{id:'q7',question:'Where was Nicholas during the crisis?',options:['Army headquarters','The Tauride Palace','Finland Station','Moscow Soviet'],correct:'Army headquarters'},{id:'q8',question:'Why could Nicholas not easily return?',options:['Railway routes were blocked','He had already left Russia','The Duma arrested him in Petrograd','The navy refused transport'],correct:'Railway routes were blocked'},{id:'q9',question:'When did Nicholas abdicate?',options:['2 March 1917','25 October 1917','3 March 1918','9 January 1905'],correct:'2 March 1917'},{id:'q10',question:'What is the strongest overall judgement?',options:['Mutiny made wider wartime and political weaknesses fatal','Bread shortages alone explain everything','The Bolsheviks directed the whole revolution','The monarchy remained in control'],correct:'Mutiny made wider wartime and political weaknesses fatal'}];
export const februaryRevolutionJudgement={question:'Rank the causes of the February Revolution.',factors:[{id:'war',title:'War pressures',detail:'Casualties, inflation and shortages weakened society.'},{id:'bread',title:'Petrograd shortages',detail:'Queues and hardship triggered protest.'},{id:'women',title:'Women’s action',detail:'Women workers initiated the first mass demonstrations.'},{id:'strikes',title:'General strike',detail:'Industrial protest paralysed the capital.'},{id:'mutiny',title:'Army mutiny',detail:'The regime lost coercive power.'},{id:'duma',title:'Duma action',detail:'Deputies created an alternative authority.'},{id:'soviet',title:'Petrograd Soviet',detail:'Workers and soldiers organised political power.'},{id:'nicholas',title:'Nicholas II',detail:'Misjudgement and isolation accelerated collapse.'}]};
export const februaryRevolutionAO3={question:'Evaluate each interpretation separately using precise contextual knowledge.',interpretations:[{historian:'Interpretation A',argument:'The revolution was primarily a spontaneous urban uprising caused by wartime shortages and popular anger.'},{historian:'Interpretation B',argument:'The decisive cause was the mutiny of the Petrograd garrison, which removed the regime’s coercive power.'},{historian:'Interpretation C',argument:'Nicholas fell because political and military elites abandoned him once they believed the monarchy could no longer sustain the war.'}]};
export const februaryRevolutionPeel={question:'“The mutiny of the Petrograd garrison was the main reason for the success of the February Revolution.” Assess the validity of this view.',stretchQuestion:'Write a causal plan linking long-term, wartime and immediate factors.',scaffold:['Define success.','Separate background pressures from triggers.','Use women’s protests and strikes.','Explain why mutiny was a turning point.','Include the Duma and generals.','Reach a comparative judgement.']};
export const februaryRevolutionConfidence={prompt:'How confident are you explaining the February Revolution?',leastSecureOptions:['Bread crisis','Women protesters','Strikes','Garrison mutiny','Duma Committee','Petrograd Soviet','Order Number 1','Nicholas II','Abdication'],scale:[1,2,3,4,5]};
export const februaryRevolutionFallbacks:Record<string,any>={lesson_content:{sections:februaryRevolutionLessonSections},timeline:februaryRevolutionTimeline,flashcards:{cards:februaryRevolutionFlashcards},quiz:{questions:februaryRevolutionQuiz},judgement_ranking:februaryRevolutionJudgement,ao3_interpretation:februaryRevolutionAO3,peel_response:februaryRevolutionPeel,confidence_exit_ticket:februaryRevolutionConfidence};