export const leninIdeologyChangePathwaySlug='lenin-ideology-change';
const sections=[
{heading:'The October inheritance',body:'The Bolsheviks seized power in a country exhausted by war, economic collapse and political fragmentation. Lenin presented October as soviet power, but Bolshevik control depended on a disciplined party and rapid central decisions.',question:'What problems confronted the new regime?',taskType:'judgement'},
{heading:'Marxism and Leninism',body:'Lenin adapted Marxism to Russian conditions: a vanguard party would lead workers, seize power and defend the revolution during a transitional dictatorship of the proletariat.',question:'How far was Leninism a departure from Marx?',taskType:'comparison'},
{heading:'Sovnarkom and decrees',body:'The Council of People’s Commissars issued decrees on land, peace, workers’ control and nationalities. These measures mixed ideological aims with pragmatic attempts to secure support.',question:'Which early decree mattered most?',taskType:'judgement'},
{heading:'Constituent Assembly',body:'When the Socialist Revolutionaries won the November 1917 election, the Bolsheviks dissolved the Assembly in January 1918. Lenin argued soviets represented a higher form of democracy.',question:'Did dissolution make dictatorship inevitable?',taskType:'judgement'},
{heading:'Treaty of Brest-Litovsk',body:'Russia left the war in March 1918 at enormous territorial and economic cost. Lenin prioritised survival of the revolution over national interest and faced opposition inside his own party.',question:'Ideology or pragmatism?',taskType:'comparison'},
{heading:'One-party government',body:'Opposition parties were restricted, the Cheka expanded and decision-making concentrated in party institutions. Civil conflict accelerated trends already visible before full-scale war.',question:'When did one-party dictatorship begin?',taskType:'judgement'},
{heading:'Overall judgement',body:'Lenin’s Russia was shaped by ideology, but ideology was repeatedly adapted to circumstances. The strongest explanation combines Bolshevik beliefs, wartime emergency and Lenin’s political choices.',question:'How far was Lenin’s Russia shaped by ideology?',taskType:'judgement'}];
const timeline={events:[{id:'oct17',date:'Oct 1917',title:'Bolsheviks seize power',detail:'Sovnarkom replaces the Provisional Government.'},{id:'nov17',date:'Nov 1917',title:'Constituent Assembly election',detail:'SRs win the largest share.'},{id:'jan18',date:'Jan 1918',title:'Assembly dissolved',detail:'Bolsheviks close Russia’s elected parliament.'},{id:'mar18',date:'Mar 1918',title:'Brest-Litovsk',detail:'Russia exits the First World War.'},{id:'jul18',date:'Jul 1918',title:'1918 Constitution',detail:'The Russian Soviet Federative Socialist Republic is established.'}]};
const flashcards=[['Vanguard party','A disciplined revolutionary party leading the working class.'],['Sovnarkom','Council of People’s Commissars headed by Lenin.'],['Decree on Land','Recognised peasant seizures of landed estates.'],['Decree on Peace','Called for an immediate peace without annexations.'],['Workers’ control','Factory committees gained supervisory powers.'],['Constituent Assembly','Elected body dissolved by Bolsheviks in January 1918.'],['Brest-Litovsk','Treaty ending Russia’s participation in the First World War.'],['Cheka','Political police created in December 1917.'],['Democratic centralism','Debate followed by unity in implementing party decisions.'],['Dictatorship of proletariat','Transitional rule claimed to defend workers’ power.'],['Ideology','A coherent system of political beliefs.'],['Pragmatism','Adapting policy to immediate circumstances.']].map((x,i)=>({id:`f${i+1}`,front:x[0],back:x[1]}));
const quiz=[['Who chaired Sovnarkom?','Lenin'],['Which election did the SRs win?','Constituent Assembly'],['When was the Assembly dissolved?','January 1918'],['Which treaty ended Russia’s war?','Brest-Litovsk'],['What was the Cheka?','Political police'],['What did the Decree on Land recognise?','Peasant land seizures'],['What was democratic centralism?','Unity after party debate'],['What was Lenin’s revolutionary party called?','Vanguard party'],['What did Sovnarkom replace?','Provisional Government'],['Best overall judgement?','Ideology was adapted through pragmatic choices']].map((x,i)=>({id:`q${i+1}`,question:x[0],options:[x[1],...['The Duma','The Tsar','The zemstva'].filter(y=>y!==x[1])],correct:x[1]}));
const judgement={question:'Rank the forces shaping Lenin’s new state.',factors:['Marxist ideology','Lenin’s leadership','Civil emergency','Need for popular support','Party organisation','Opposition weakness'].map((title,i)=>({id:`j${i+1}`,title,detail:'Assess significance using precise evidence from 1917–18.'}))};
const ao3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Lenin consistently pursued a revolutionary ideological programme.'},{historian:'Interpretation B',argument:'Emergency and survival mattered more than doctrine.'},{historian:'Interpretation C',argument:'Lenin used ideology to justify increasingly centralised party rule.'}]};
const peel={question:'“Ideology was the main influence on Lenin’s government in 1917–18.” Assess the validity of this view.',stretchQuestion:'Write an introduction distinguishing aims, methods and outcomes.',scaffold:['Define ideology and pragmatism.','Use decrees, the Assembly and Brest-Litovsk.','Compare belief with circumstance.','Reach a sustained judgement.']};
const confidence={prompt:'How confident are you judging ideology and pragmatism under Lenin?',leastSecureOptions:['Marxism','Leninism','Sovnarkom','Decrees','Assembly','Brest-Litovsk','Cheka','One-party rule'],scale:[1,2,3,4,5]};
export const leninIdeologyChangeFallbacks:Record<string,any>={lesson_content:{sections},timeline,flashcards:{cards:flashcards},quiz:{questions:quiz},judgement_ranking:judgement,ao3_interpretation:ao3,peel_response:peel,confidence_exit_ticket:confidence};