type Section={heading:string;body:string;question:string;taskType:string};
type Event={id:string;date:string;title:string;detail:string};
type LessonSeed={slug:string;sections:Section[];events:Event[];terms:[string,string][];quiz:[string,string][];judgementQuestion:string;factors:string[];interpretations:string[];essayQuestion:string;stretch:string;confidence:string[]};

function buildLesson(seed:LessonSeed){
 const flashcards=seed.terms.map((x,i)=>({id:`f${i+1}`,front:x[0],back:x[1]}));
 const distractors=['Collectivisation','The New Economic Policy','The Great Terror','Socialism in One Country'];
 const quiz=seed.quiz.map((x,i)=>({id:`q${i+1}`,question:x[0],options:[x[1],...distractors.filter(y=>y!==x[1]).slice(0,3)],correct:x[1]}));
 return {slug:seed.slug,fallbacks:{lesson_content:{sections:seed.sections},timeline:{events:seed.events},flashcards:{cards:flashcards},quiz:{questions:quiz},judgement_ranking:{question:seed.judgementQuestion,factors:seed.factors.map((title,i)=>({id:`j${i+1}`,title,detail:'Rank this factor and support it with precise evidence.'}))},ao3_interpretation:{question:'Evaluate each interpretation separately using relevant contextual knowledge.',interpretations:seed.interpretations.map((argument,i)=>({historian:`Interpretation ${String.fromCharCode(65+i)}`,argument}))},peel_response:{question:seed.essayQuestion,stretchQuestion:seed.stretch,scaffold:['Define the key judgement in the question.','Develop two or three supported factors.','Compare relative importance and limits.','Reach a sustained overall judgement.']},confidence_exit_ticket:{prompt:`How confident are you with ${seed.slug.replaceAll('-',' ')}?`,leastSecureOptions:seed.confidence,scale:[1,2,3,4,5]}}};
}

export const greatTurnLesson=buildLesson({slug:'great-turn-end-nep',sections:[
 {heading:'Why Stalin abandoned NEP',body:'By 1928 Stalin argued that NEP could not supply grain, finance rapid industrialisation or secure the USSR against foreign attack. The grain procurement crisis strengthened the case for coercion.',question:'Why did Stalin reject gradual development?',taskType:'explain'},
 {heading:'The Great Turn',body:'The Great Turn of 1928–29 replaced NEP with forced collectivisation, central planning and rapid industrialisation. It represented a sharp change in economic method and the balance of power within the Party.',question:'How far was 1928–29 a turning point?',taskType:'judgement'},
 {heading:'Ideology and security',body:'Stalin presented transformation as a socialist offensive against capitalist elements and as preparation for an expected war. Economic modernisation was tied to political survival.',question:'Was ideology or security more important?',taskType:'comparison'},
 {heading:'Defeat of the Right',body:'Bukharin, Rykov and Tomsky favoured continuing NEP and encouraging peasants. Stalin used control of appointments and Party procedure to isolate them.',question:'Why was the Right defeated?',taskType:'explain'},
 {heading:'Overall judgement',body:'The Great Turn combined economic pressure, ideological ambition and Stalin’s struggle for supremacy. It ended the mixed economy and opened the era of command planning.',question:'What best explains the Great Turn?',taskType:'judgement'}],events:[{id:'grain',date:'1927–28',title:'Grain procurement crisis',detail:'State collections fall and coercive measures increase.'},{id:'ural',date:'Jan 1928',title:'Urals-Siberian method',detail:'Officials seize grain from supposedly wealthy peasants.'},{id:'plan',date:'1928',title:'First Five-Year Plan begins',detail:'Central targets prioritise heavy industry.'},{id:'turn',date:'1929',title:'Great Turn',detail:'Stalin commits to mass collectivisation and attacks the Right.'}],terms:[['Great Turn','The decisive shift from NEP to collectivisation and rapid industrialisation.'],['Procurement crisis','Failure of the state to obtain sufficient marketable grain.'],['Right Opposition','Bukharin, Rykov and Tomsky, who defended gradual NEP development.'],['Urals-Siberian method','Coercive grain seizure and punitive taxation.'],['Command economy','Production directed by compulsory state plans.'],['Socialism in One Country','Stalin’s claim that socialism could be built within the USSR.']],quiz:[['What crisis accelerated the end of NEP?','Grain procurement crisis'],['Which group defended NEP?','Right Opposition'],['When did the First Five-Year Plan begin?','1928'],['What replaced market direction?','Command economy'],['Who was the leading Right critic of Stalin?','Bukharin'],['What did the Great Turn launch?','Collectivisation']],judgementQuestion:'Rank the reasons Stalin launched the Great Turn.',factors:['Grain procurement crisis','Need for industrial finance','Fear of foreign war','Socialist ideology','Defeat of the Right','Stalin’s personal power'],interpretations:['The Great Turn was principally an improvised response to economic crisis.','The Great Turn was the logical outcome of Bolshevik ideology.','Stalin used economic transformation to complete his political victory.'],essayQuestion:'“The main reason Stalin abandoned NEP was the grain procurement crisis.” Assess the validity of this view.',stretch:'Distinguish immediate triggers from deeper objectives.',confidence:['Grain crisis','Ideology','Security','Right Opposition','Political power','Turning point']});

export const collectivisationLesson=buildLesson({slug:'collectivisation',sections:[
 {heading:'Aims',body:'Collectivisation aimed to increase state control of grain, release labour for industry, mechanise farming and destroy the economic independence of the peasantry.',question:'Which aim mattered most?',taskType:'judgement'},
 {heading:'Dekulakisation',body:'The regime labelled better-off or resistant peasants as kulaks. Property was confiscated and hundreds of thousands of families were deported, imprisoned or killed.',question:'Why was dekulakisation central?',taskType:'explain'},
 {heading:'Mass collectivisation',body:'Peasants were forced into collective farms. Resistance included slaughtering livestock, hiding grain and attacking officials. Stalin briefly blamed local excesses in Dizzy with Success.',question:'How effective was resistance?',taskType:'judgement'},
 {heading:'Famine',body:'Disruption, requisitioning and punitive policies contributed to catastrophic famine in 1932–33, particularly in Ukraine, Kazakhstan and grain-producing regions.',question:'How far was famine a consequence of policy?',taskType:'judgement'},
 {heading:'Results',body:'The state secured control over procurement and rural society, but productivity remained weak and human costs were enormous. Collectivisation was politically effective but economically damaging.',question:'Was collectivisation successful?',taskType:'comparison'}],events:[{id:'drive',date:'1929',title:'Mass collectivisation drive',detail:'Stalin calls for the liquidation of kulaks as a class.'},{id:'dizzy',date:'Mar 1930',title:'Dizzy with Success',detail:'Stalin temporarily criticises excessive coercion.'},{id:'famine',date:'1932–33',title:'Famine',detail:'Millions die amid requisitioning and agricultural disruption.'},{id:'complete',date:'1937',title:'Most farms collectivised',detail:'The great majority of peasant households are in collectives.'}],terms:[['Collective farm','A farm worked jointly under state direction.'],['Kolkhoz','Collective farm whose members retained small private plots.'],['Sovkhoz','State farm with wage-paid workers.'],['Dekulakisation','Removal, deportation or destruction of alleged kulaks.'],['MTS','Machine Tractor Stations supplying machinery and political supervision.'],['Procurement quota','Compulsory grain delivery target set by the state.']],quiz:[['What was dekulakisation?','Destruction of alleged kulaks'],['What was a kolkhoz?','Collective farm'],['What did peasants slaughter in resistance?','Livestock'],['When was the major famine?','1932–33'],['What were MTS?','Machine Tractor Stations'],['What did the state gain?','Control of grain']],judgementQuestion:'Rank the successes and failures of collectivisation.',factors:['State grain control','Industrial labour supply','Mechanisation','Peasant resistance','Famine','Long-term productivity'],interpretations:['Collectivisation was an economic catastrophe imposed by terror.','Collectivisation achieved Stalin’s essential political and procurement objectives.','Peasant resistance shaped the uneven course of collectivisation.'],essayQuestion:'“Collectivisation was successful because it strengthened state control.” Assess the validity of this view.',stretch:'Separate political success from economic and human outcomes.',confidence:['Aims','Dekulakisation','Resistance','Famine','Farm types','Results']});

export const fiveYearPlansLesson=buildLesson({slug:'five-year-plans',sections:[
 {heading:'Planning and priorities',body:'Gosplan set ambitious targets, concentrating investment on coal, steel, electricity, engineering and defence. Consumer production and living standards were subordinated.',question:'Why was heavy industry prioritised?',taskType:'explain'},
 {heading:'First Plan',body:'The First Five-Year Plan produced rapid expansion and huge new projects such as Magnitogorsk and Dnieperstroi, although targets were chaotic and statistics unreliable.',question:'How successful was the First Plan?',taskType:'judgement'},
 {heading:'Labour and coercion',body:'Workers faced strict discipline, internal passports, wage differentials and criminal penalties. Gulag labour contributed to major construction and resource projects.',question:'How important was coercion?',taskType:'judgement'},
 {heading:'Stakhanovism',body:'From 1935 model workers were celebrated for exceeding norms. The campaign encouraged productivity but also raised targets and intensified pressure on ordinary workers.',question:'Was Stakhanovism incentive or propaganda?',taskType:'comparison'},
 {heading:'Overall results',body:'The USSR became a major industrial power with stronger defence capacity, but production was wasteful, quality poor and consumer life harsh.',question:'How far did the plans modernise the USSR?',taskType:'judgement'}],events:[{id:'first',date:'1928–32',title:'First Five-Year Plan',detail:'Heavy industrial expansion begins.'},{id:'second',date:'1933–37',title:'Second Five-Year Plan',detail:'Transport, engineering and defence grow further.'},{id:'stakh',date:'1935',title:'Stakhanov movement',detail:'Record-breaking labour becomes a national campaign.'},{id:'third',date:'1938',title:'Third Plan',detail:'Defence receives increasing priority before war.'}],terms:[['Gosplan','State planning agency responsible for economic targets.'],['Five-Year Plan','Compulsory programme of production targets.'],['Magnitogorsk','Major new iron and steel industrial city.'],['Stakhanovite','Worker promoted for exceptional output.'],['Gulag labour','Forced labour used in construction and extraction.'],['Shock worker','Worker expected to exceed production norms.']],quiz:[['Which body set economic targets?','Gosplan'],['What received priority?','Heavy industry'],['What was Magnitogorsk?','Industrial city'],['When did Stakhanovism begin?','1935'],['What was neglected?','Consumer goods'],['What increased before war?','Defence production']],judgementQuestion:'Rank the achievements and costs of the Five-Year Plans.',factors:['Heavy industrial growth','Defence capacity','Urbanisation','Labour coercion','Consumer shortages','Waste and poor quality'],interpretations:['The plans created the industrial base that enabled Soviet survival in war.','Claims of achievement were distorted by coercion, waste and unreliable data.','Industrialisation transformed society as profoundly as it transformed output.'],essayQuestion:'“The Five-Year Plans were a remarkable economic success.” Assess the validity of this view.',stretch:'Judge output, efficiency, defence and living standards separately.',confidence:['Gosplan','First Plan','Second Plan','Labour','Stakhanovism','Overall results']});

export const societyCultureLesson=buildLesson({slug:'stalinist-society-culture',sections:[
 {heading:'Urban transformation',body:'Industrialisation drew millions into rapidly expanding towns. Housing, sanitation and food supplies struggled to keep pace, while social mobility opened for some workers and specialists.',question:'Who benefited from urban change?',taskType:'judgement'},
 {heading:'Education and specialists',body:'The regime expanded literacy, technical education and training. After early hostility to experts, skilled managers and professionals received higher rewards and status.',question:'How equal was Stalinist society?',taskType:'comparison'},
 {heading:'Women and family',body:'Women entered paid work in large numbers but retained domestic burdens. The 1936 Family Code restricted abortion and promoted marriage, motherhood and population growth.',question:'Did Stalinism liberate women?',taskType:'judgement'},
 {heading:'Culture and Socialist Realism',body:'Writers and artists were required to present optimistic, accessible images of socialist construction. Censorship and professional unions enforced conformity.',question:'How did culture serve dictatorship?',taskType:'explain'},
 {heading:'Religion and nationalities',body:'Churches were closed and clergy persecuted, though religious practice survived. Russification and central control increasingly limited the earlier promotion of national cultures.',question:'How complete was cultural control?',taskType:'judgement'}],events:[{id:'literacy',date:'1930',title:'Compulsory primary education',detail:'The state expands mass schooling.'},{id:'realism',date:'1932–34',title:'Socialist Realism imposed',detail:'Independent artistic organisations are replaced by state unions.'},{id:'family',date:'1936',title:'Family Code',detail:'Abortion is restricted and family stability promoted.'},{id:'census',date:'1937',title:'Suppressed census',detail:'Unwelcome demographic and religious findings are concealed.'}],terms:[['Socialist Realism','Official artistic style celebrating socialist construction.'],['Cultural Revolution','Campaign against bourgeois specialists and traditional culture.'],['Family Code','1936 law promoting marriage and motherhood.'],['Internal passport','Document controlling residence and movement.'],['Social mobility','Movement into skilled, managerial or professional roles.'],['Russification','Promotion of Russian language and central culture.']],quiz:[['What was the official art style?','Socialist Realism'],['What did the 1936 law restrict?','Abortion'],['What expanded rapidly?','Urban population'],['Who received greater rewards?','Specialists'],['What controlled residence?','Internal passport'],['What policy promoted Russian culture?','Russification']],judgementQuestion:'Rank the extent of change in Stalinist society and culture.',factors:['Education and literacy','Urbanisation','Women and family','Social mobility','Cultural control','Religion and nationalities'],interpretations:['Stalinism created genuine opportunities for education and social advancement.','Social transformation imposed new burdens and reinforced hierarchy.','Culture became a central instrument for mobilising and disciplining society.'],essayQuestion:'“Stalinist social policy brought more opportunity than oppression.” Assess the validity of this view.',stretch:'Compare experience by gender, class, age and location.',confidence:['Urbanisation','Education','Women','Family Code','Culture','Religion']});

export const greatTerrorLesson=buildLesson({slug:'great-terror',sections:[
 {heading:'Origins',body:'Fear of opposition, tensions generated by rapid transformation, Stalin’s personal insecurity and the murder of Sergei Kirov in 1934 all contributed to escalating repression.',question:'What best explains the Terror?',taskType:'judgement'},
 {heading:'Show trials',body:'Old Bolsheviks including Zinoviev, Kamenev and Bukharin confessed to fabricated conspiracies in highly publicised trials. Most were executed.',question:'Why were show trials useful?',taskType:'explain'},
 {heading:'Mass operations',body:'NKVD Order 00447 established quotas for arrests and executions of alleged anti-Soviet elements. National operations and regional initiatives widened terror far beyond Party elites.',question:'Was the Terror centrally controlled?',taskType:'judgement'},
 {heading:'Army and institutions',body:'Military commanders, officials, managers and professionals were purged. Promotion opportunities followed, but expertise and initiative were damaged.',question:'How did purges strengthen and weaken Stalin?',taskType:'comparison'},
 {heading:'Scale and consequences',body:'Hundreds of thousands were executed and many more sent to camps. Terror destroyed alternative centres of authority and encouraged conformity, denunciation and fear.',question:'How effective was terror as control?',taskType:'judgement'}],events:[{id:'kirov',date:'Dec 1934',title:'Kirov murdered',detail:'The assassination becomes a pretext for wider repression.'},{id:'trial1',date:'1936',title:'First Moscow Trial',detail:'Zinoviev and Kamenev are condemned.'},{id:'order',date:'Jul 1937',title:'Order 00447',detail:'Mass operations and arrest quotas accelerate.'},{id:'buk',date:'1938',title:'Bukharin trial',detail:'Leading former opponents are eliminated.'}],terms:[['NKVD','Secret police organisation responsible for mass repression.'],['Show trial','Public trial based on forced confession and fabricated charges.'],['Order 00447','Directive launching mass operations against alleged enemies.'],['Quota','Numerical target for arrest, execution or imprisonment.'],['Yezhovshchina','Period of intense terror under NKVD chief Nikolai Yezhov.'],['Gulag','System of forced-labour camps.']],quiz:[['Whose murder preceded escalation?','Kirov'],['Which organisation conducted arrests?','NKVD'],['What did Order 00447 establish?','Quotas'],['Who was tried in 1938?','Bukharin'],['What were public political prosecutions called?','Show trials'],['What was the camp system called?','Gulag']],judgementQuestion:'Rank the causes and consequences of the Great Terror.',factors:['Stalin’s insecurity','Kirov murder','Institutional pressures','Local initiative','Elimination of rivals','Damage to expertise'],interpretations:['The Great Terror was primarily directed and shaped by Stalin.','Institutional competition and local initiative made terror broader and less controlled.','Terror was rooted in the crises created by forced transformation.'],essayQuestion:'“Stalin’s personal insecurity was the main cause of the Great Terror.” Assess the validity of this view.',stretch:'Distinguish responsibility, mechanism and wider conditions.',confidence:['Origins','Kirov','Show trials','Mass operations','Army purge','Consequences']});

export const stalinDictatorshipLesson=buildLesson({slug:'stalin-dictatorship-control',sections:[
 {heading:'Party and state',body:'Formal Soviet institutions remained, but real authority centred on Stalin, the Politburo, the Secretariat and personal networks. Appointments tied officials to the leadership.',question:'How personal was Stalin’s power?',taskType:'judgement'},
 {heading:'Cult of personality',body:'Propaganda portrayed Stalin as Lenin’s heir, brilliant theorist, caring father and architect of every achievement. History and images were rewritten to elevate him.',question:'Why did the cult matter?',taskType:'explain'},
 {heading:'Propaganda and censorship',body:'Press, radio, film, education and public ritual promoted official values. Glavlit censored information, while achievements were celebrated and failures concealed.',question:'Could propaganda create genuine support?',taskType:'comparison'},
 {heading:'Surveillance and participation',body:'Control relied on secret police, workplace discipline and denunciation, but also on promotion, education, youth organisations and participation in state campaigns.',question:'Was rule based only on fear?',taskType:'judgement'},
 {heading:'The 1936 Constitution',body:'The constitution promised democratic rights and universal suffrage while one-party dictatorship and repression intensified. It projected legitimacy without limiting Stalin’s authority.',question:'Why preserve constitutional forms?',taskType:'judgement'},
 {heading:'Overall judgement',body:'By 1941 Stalin dominated political life through institutions, patronage, propaganda and terror. Yet the system also depended on millions of officials and citizens interpreting and implementing policy.',question:'How total was Stalin’s dictatorship?',taskType:'judgement'}],events:[{id:'lenin',date:'1924 onward',title:'Stalin as Lenin’s heir',detail:'Propaganda increasingly links Stalin to Lenin.'},{id:'short',date:'1938',title:'Short Course published',detail:'Official Party history elevates Stalin’s role.'},{id:'const',date:'1936',title:'Stalin Constitution',detail:'Formal rights are proclaimed amid dictatorship.'},{id:'war',date:'1941',title:'Personal dictatorship entrenched',detail:'Stalin dominates Party, state and armed forces.'}],terms:[['Cult of personality','Systematic glorification of Stalin as an exceptional leader.'],['Nomenklatura','Key positions filled through Party-controlled appointment.'],['Secretariat','Party body controlling organisation and personnel.'],['Glavlit','Main censorship authority.'],['Short Course','Official history of the Communist Party published in 1938.'],['Komsomol','Communist youth organisation.']],quiz:[['What controlled key appointments?','Nomenklatura'],['What was Glavlit?','Censorship authority'],['What portrayed Stalin as Lenin’s heir?','Cult of personality'],['When was the Stalin Constitution?','1936'],['What was Komsomol?','Youth organisation'],['What official history appeared in 1938?','Short Course']],judgementQuestion:'Rank the foundations of Stalin’s dictatorship.',factors:['Party appointments','Personal patronage','Terror','Propaganda','Cult of personality','Popular participation'],interpretations:['Stalin’s dictatorship rested above all on terror.','Institutional control and patronage were more durable than episodic terror.','The regime combined coercion with opportunities that generated participation and support.'],essayQuestion:'“Terror was the most important means by which Stalin maintained control by 1941.” Assess the validity of this view.',stretch:'Compare coercion, institutions, propaganda and participation.',confidence:['Party control','Appointments','Cult','Propaganda','Constitution','Overall judgement']});