export const russiaFirstWorldWarPathwaySlug='russia-first-world-war';
export const russiaFirstWorldWarLessonSections=[
{heading:'The enquiry',body:'The First World War placed exceptional pressure on Russia’s army, economy, society and political system. The key issue is whether war created collapse or exposed weaknesses that already existed.',question:'How did war weaken Tsarism?',taskType:'judgement'},
{heading:'Initial support',body:'War was initially greeted with patriotic enthusiasm and the capital was renamed Petrograd. Political parties largely supported the government, but unity proved temporary as casualties and shortages mounted.',question:'Why did early unity fade?',taskType:'explain'},
{heading:'Military failures',body:'Russia suffered huge losses at Tannenberg and the Masurian Lakes in 1914. Although the army later recovered some ground, shortages of weapons, shells, boots and trained officers damaged morale.',question:'How important were military defeats?',taskType:'judgement'},
{heading:'Nicholas takes command',body:'In September 1915 Nicholas II became commander-in-chief. This tied his personal reputation directly to military performance and left Alexandra more influential in Petrograd.',question:'Why was this decision politically risky?',taskType:'judgement'},
{heading:'Economic disruption',body:'Mobilisation removed millions of workers and peasants from production. Railway congestion, inflation and shortages reduced the supply of food and fuel to towns even when grain existed elsewhere.',question:'Was shortage caused by production or distribution?',taskType:'comparison'},
{heading:'Workers and cities',body:'Real wages fell as prices rose. Queues lengthened, strikes increased and urban workers blamed the government for food and fuel shortages.',question:'How did economic hardship become political opposition?',taskType:'explain'},
{heading:'Peasants and soldiers',body:'Peasant soldiers endured casualties, poor leadership and separation from their farms. Desertion and indiscipline increased, while rural families faced labour shortages and inflation.',question:'Why did army morale deteriorate?',taskType:'judgement'},
{heading:'Government and the Duma',body:'The Progressive Bloc called for a ministry enjoying public confidence. Nicholas rejected cooperation and repeatedly changed ministers, deepening the impression of incompetence.',question:'How far did political mismanagement worsen the crisis?',taskType:'judgement'},
{heading:'Alexandra and Rasputin',body:'Alexandra’s German birth and reliance on Rasputin fuelled rumours of treachery and corruption. Rasputin’s influence was exaggerated, but the scandal damaged the monarchy’s legitimacy.',question:'Why did perception matter?',taskType:'judgement'},
{heading:'Overall judgement',body:'War transformed chronic weaknesses into an immediate crisis. Military casualties, economic dislocation and political isolation interacted, while Nicholas’s decisions made the monarchy personally responsible for failure.',question:'How decisive was the war in the fall of Tsarism?',taskType:'judgement'}];
export const russiaFirstWorldWarTimeline={events:[{id:'1914a',date:'August 1914',title:'Russia enters war',detail:'Patriotic support briefly strengthens the regime.'},{id:'1914b',date:'August 1914',title:'Tannenberg',detail:'A major defeat exposes command and communication failures.'},{id:'1915',date:'September 1915',title:'Nicholas takes command',detail:'The Tsar links himself directly to the army’s fortunes.'},{id:'1915b',date:'1915',title:'Progressive Bloc',detail:'Duma politicians demand a government with public confidence.'},{id:'1916',date:'December 1916',title:'Rasputin murdered',detail:'Elite conspirators fail to restore confidence in the monarchy.'},{id:'1917',date:'February 1917',title:'Petrograd crisis',detail:'Shortages, strikes and mutiny bring down Tsarism.'}]};
export const russiaFirstWorldWarFlashcards=[{id:'tannenberg',front:'Tannenberg',back:'Major Russian defeat by Germany in August 1914.'},{id:'mobilisation',front:'Mobilisation',back:'Calling millions of men into the armed forces.'},{id:'inflation',front:'Inflation',back:'Rapid price rises that reduced real wages.'},{id:'railways',front:'Railway crisis',back:'Transport congestion that disrupted food and fuel supplies.'},{id:'command',front:'Commander-in-chief',back:'Role Nicholas II assumed in September 1915.'},{id:'bloc',front:'Progressive Bloc',back:'Duma alliance demanding a ministry with public confidence.'},{id:'ministerial',front:'Ministerial leapfrog',back:'Frequent changes of ministers that suggested instability.'},{id:'rasputin',front:'Rasputin',back:'Mystic whose association with the court damaged royal prestige.'},{id:'alexandra',front:'Alexandra',back:'Empress whose German background fuelled wartime suspicion.'},{id:'desertion',front:'Desertion',back:'Soldiers abandoning their units as morale collapsed.'},{id:'legitimacy',front:'Legitimacy crisis',back:'Loss of belief that the monarchy deserved to rule.'},{id:'interaction',front:'Interaction of causes',back:'Military, economic, social and political pressures reinforcing one another.'}];
export const russiaFirstWorldWarQuiz=[{id:'q1',question:'Where was Russia badly defeated in August 1914?',options:['Tannenberg','Tsushima','Kazan','Kronstadt'],correct:'Tannenberg'},{id:'q2',question:'What role did Nicholas assume in 1915?',options:['Commander-in-chief','Chairman of the Soviet','Prime minister','War minister'],correct:'Commander-in-chief'},{id:'q3',question:'What happened to prices during the war?',options:['They rose rapidly','They disappeared','They were fixed successfully','They fell sharply'],correct:'They rose rapidly'},{id:'q4',question:'What disrupted urban food supply?',options:['Railway congestion','Excess imports','Universal rationing from 1914','Abolition of farming'],correct:'Railway congestion'},{id:'q5',question:'What did the Progressive Bloc demand?',options:['A ministry with public confidence','Immediate Bolshevik rule','Restoration of serfdom','Withdrawal from all politics'],correct:'A ministry with public confidence'},{id:'q6',question:'Why did Nicholas taking command weaken him?',options:['He became associated with military failure','He gained control of the Duma','He ended inflation','He removed Alexandra'],correct:'He became associated with military failure'},{id:'q7',question:'Why was Alexandra unpopular?',options:['German birth and Rasputin association','Leadership of the Kadets','Support for the Soviet','Command of the army'],correct:'German birth and Rasputin association'},{id:'q8',question:'What happened to soldier morale?',options:['It deteriorated','It remained uniformly high','It ended all desertion','It produced victory'],correct:'It deteriorated'},{id:'q9',question:'What is ministerial leapfrog?',options:['Frequent ministerial changes','A military tactic','A peasant commune','A Duma election law'],correct:'Frequent ministerial changes'},{id:'q10',question:'What is the strongest judgement?',options:['War exposed and intensified existing weaknesses','War had no political effect','Military defeat alone explains everything','The economy remained stable'],correct:'War exposed and intensified existing weaknesses'}];
export const russiaFirstWorldWarJudgement={question:'Rank the wartime causes of Tsarist collapse.',factors:[{id:'military',title:'Military failure',detail:'Casualties, defeats and shortages damaged morale.'},{id:'economy',title:'Economic disruption',detail:'Inflation and transport breakdown hit towns.'},{id:'workers',title:'Worker unrest',detail:'Strikes linked hardship to politics.'},{id:'soldiers',title:'Army morale',detail:'Desertion and mutiny undermined coercive power.'},{id:'nicholas',title:'Nicholas II',detail:'His command decision personalised failure.'},{id:'duma',title:'Political isolation',detail:'The Tsar rejected the Progressive Bloc.'},{id:'court',title:'Court scandal',detail:'Alexandra and Rasputin damaged legitimacy.'},{id:'structure',title:'Pre-war weaknesses',detail:'Land, labour and political grievances predated war.'}]};
export const russiaFirstWorldWarAO3={question:'Evaluate each interpretation separately using precise contextual knowledge.',interpretations:[{historian:'Interpretation A',argument:'Military defeat was the decisive cause because it destroyed the army’s loyalty and the Tsar’s authority.'},{historian:'Interpretation B',argument:'Economic dislocation in the cities turned wartime strain into mass political protest.'},{historian:'Interpretation C',argument:'War was a catalyst rather than a complete explanation because Tsarism entered the conflict with deep structural weaknesses.'}]};
export const russiaFirstWorldWarPeel={question:'“The First World War was the main reason for the collapse of Tsarism.” Assess the validity of this view.',stretchQuestion:'Build a thematic plan showing how wartime and pre-war causes interacted.',scaffold:['Define collapse.','Use military, economic, social and political themes.','Explain Nicholas’s command decision.','Use the Progressive Bloc and court crisis.','Link shortages to strikes and mutiny.','Reach a comparative judgement.']};
export const russiaFirstWorldWarConfidence={prompt:'How confident are you explaining how war weakened Tsarism?',leastSecureOptions:['Military failures','Nicholas as commander','Inflation','Railways','Workers','Soldiers','Duma','Alexandra and Rasputin','War vs long-term causes'],scale:[1,2,3,4,5]};
export const russiaFirstWorldWarFallbacks:Record<string,any>={lesson_content:{sections:russiaFirstWorldWarLessonSections},timeline:russiaFirstWorldWarTimeline,flashcards:{cards:russiaFirstWorldWarFlashcards},quiz:{questions:russiaFirstWorldWarQuiz},judgement_ranking:russiaFirstWorldWarJudgement,ao3_interpretation:russiaFirstWorldWarAO3,peel_response:russiaFirstWorldWarPeel,confidence_exit_ticket:russiaFirstWorldWarConfidence};