export const bolshevikConsolidationPathwaySlug='bolshevik-consolidation';
const sections=[
{heading:'Securing October',body:'The Bolsheviks controlled Petrograd but not the whole former empire. Their survival depended on neutralising rivals, building institutions and presenting themselves as the legitimate revolutionary government.',question:'Why was seizure of power not the same as consolidation?',taskType:'explain'},
{heading:'Political opposition',body:'Kadets were outlawed, rival socialist newspapers were closed and the Constituent Assembly was dispersed. Mensheviks and Right SRs were later excluded from soviet institutions.',question:'How important was political repression?',taskType:'judgement'},
{heading:'The Cheka and Red Terror',body:'The Cheka attacked counter-revolution, sabotage and political opponents. After attempts on Bolshevik leaders in 1918, repression intensified through arrests, executions and hostage-taking.',question:'Was terror planned or improvised?',taskType:'comparison'},
{heading:'Church and society',body:'The regime separated Church and state, confiscated Church property and promoted secular authority. Social reforms changed marriage, divorce and women’s legal position, though implementation was uneven.',question:'How revolutionary was social policy?',taskType:'judgement'},
{heading:'Nationalities and central power',body:'The Bolsheviks proclaimed self-determination but fought to retain strategic territories. The gap between principle and practice widened as the party rebuilt central control.',question:'Why did nationality policy become contradictory?',taskType:'comparison'},
{heading:'Party dictatorship',body:'Power shifted from soviets toward party committees, Sovnarkom and the Politburo. The ban on factions in 1921 strengthened leadership control inside the Communist Party itself.',question:'How did party rule become dictatorship?',taskType:'judgement'},
{heading:'Overall judgement',body:'Consolidation resulted from popular measures, institutional innovation, opposition weakness and coercion. Repression was central, but it worked alongside organisation and political adaptability.',question:'Why did the Bolsheviks consolidate power?',taskType:'judgement'}];
const timeline={events:[{id:'dec17',date:'Dec 1917',title:'Cheka created',detail:'A political police force defends the regime.'},{id:'jan18',date:'Jan 1918',title:'Constituent Assembly dissolved',detail:'Bolsheviks reject parliamentary challenge.'},{id:'sep18',date:'Sep 1918',title:'Red Terror announced',detail:'Repression intensifies during Civil War.'},{id:'mar19',date:'Mar 1919',title:'Comintern founded',detail:'The regime promotes international revolution.'},{id:'mar21',date:'Mar 1921',title:'Ban on factions',detail:'Internal party opposition is prohibited.'}]};
const flashcards=[['Consolidation','The process of making newly acquired power secure.'],['Cheka','Bolshevik political police.'],['Red Terror','Campaign of organised political repression from 1918.'],['Kadets','Liberal party outlawed after October.'],['Left SRs','Temporary Bolshevik allies who later rebelled.'],['Comintern','Organisation promoting world communist revolution.'],['Politburo','Senior party body directing major policy.'],['Orgburo','Party body concerned with organisation and appointments.'],['Ban on factions','1921 prohibition of organised groups inside the party.'],['One-party state','System in which meaningful rival parties are excluded.'],['Self-determination','Claimed right of national groups to choose their status.'],['Secularisation','Removal of Church authority from state and public life.']].map((x,i)=>({id:`f${i+1}`,front:x[0],back:x[1]}));
const quiz=[['When was the Cheka created?','December 1917'],['Who led the Cheka?','Felix Dzerzhinsky'],['What happened to the Constituent Assembly?','It was dissolved'],['What began openly in 1918?','Red Terror'],['Which party were temporary Bolshevik allies?','Left SRs'],['What promoted world revolution?','Comintern'],['Which body made top party decisions?','Politburo'],['What was banned in 1921?','Party factions'],['What happened to Kadets?','They were outlawed'],['Best explanation for consolidation?','Organisation, coercion and adaptable policy combined']].map((x,i)=>({id:`q${i+1}`,question:x[0],options:[x[1],...['The Duma','The Okhrana','Zemstva'].filter(y=>y!==x[1])],correct:x[1]}));
const judgement={question:'Rank the reasons Bolshevik power survived.',factors:['Cheka and terror','Popular decrees','Party discipline','Weak and divided opposition','Control of central cities','Lenin’s leadership'].map((title,i)=>({id:`j${i+1}`,title,detail:'Support the ranking with evidence.'}))};
const ao3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Coercion was the decisive foundation of Bolshevik consolidation.'},{historian:'Interpretation B',argument:'Organisation and political discipline mattered more than terror.'},{historian:'Interpretation C',argument:'The Bolsheviks survived because rivals failed to offer a convincing alternative.'}]};
const peel={question:'“The Bolsheviks consolidated power mainly through repression.” Assess the validity of this view.',stretchQuestion:'Write a paragraph comparing coercion with political organisation.',scaffold:['Define consolidation.','Use the Cheka, Assembly and ban on factions.','Consider popular measures and rival weakness.','Judge relative importance.']};
const confidence={prompt:'How confident are you explaining Bolshevik consolidation?',leastSecureOptions:['Cheka','Red Terror','Opposition parties','Church','Nationalities','Politburo','Ban on factions'],scale:[1,2,3,4,5]};
export const bolshevikConsolidationFallbacks:Record<string,any>={lesson_content:{sections},timeline,flashcards:{cards:flashcards},quiz:{questions:quiz},judgement_ranking:judgement,ao3_interpretation:ao3,peel_response:peel,confidence_exit_ticket:confidence};