export const stolypinReformPathwaySlug='stolypin-reform';
export const stolypinReformLessonSections=[
{heading:'Stolypin’s appointment',body:'Peter Stolypin became Chairman of the Council of Ministers in 1906. He aimed to restore order after revolution while strengthening Tsarism through selective reform.',question:'What problem was Stolypin trying to solve?',taskType:'explain'},
{heading:'Repression',body:'Field courts-martial tried suspects rapidly and thousands were executed or exiled. The noose became known as Stolypin’s necktie.',question:'How effective was repression?',taskType:'judgement'},
{heading:'The wager on the strong',body:'Stolypin hoped prosperous independent peasants would become conservative supporters of order. His reforms allowed peasants to leave the mir and consolidate scattered strips.',question:'Why link land ownership to political stability?',taskType:'explain'},
{heading:'Land reform measures',body:'Decrees from 1906 and later laws promoted private ownership, individual farms and migration to Siberia. The Peasant Land Bank assisted purchases.',question:'How far did policy challenge the mir?',taskType:'comparison'},
{heading:'Achievements',body:'Millions applied to leave the commune, agricultural output rose in some areas and commercial farming expanded. Migration opened new land in Siberia.',question:'What evidence suggests success?',taskType:'judgement'},
{heading:'Limits',body:'Many peasants remained in communes, consolidation was uneven and population growth sustained land hunger. Reform had too little time to transform the countryside before 1914.',question:'Why were results limited?',taskType:'explain'},
{heading:'The Dumas',body:'Stolypin worked with the Third Duma after changing the electoral law in June 1907 to favour landowners and wealthier voters.',question:'Was cooperation with the Duma genuine?',taskType:'judgement'},
{heading:'The June 1907 coup',body:'The electoral change was made without constitutional approval and reduced representation for peasants, workers and national minorities.',question:'How did the coup strengthen and weaken Tsarism?',taskType:'comparison'},
{heading:'Other reforms',body:'Stolypin proposed local government expansion, education and social reform, but conservative resistance from the Tsar, court and State Council blocked much of his programme.',question:'Why did the regime obstruct its own reformer?',taskType:'judgement'},
{heading:'Overall assessment',body:'Stolypin restored short-term order and began meaningful rural change, but repression bred resentment, reform remained incomplete and Nicholas never gave him consistent backing. His assassination in 1911 ended the programme’s strongest advocate.',question:'How successful was Stolypin?',taskType:'judgement'}];
export const stolypinReformTimeline={events:[{id:'1906a',date:'April 1906',title:'Stolypin becomes Interior Minister',detail:'He takes a leading role in restoring order.'},{id:'1906b',date:'July 1906',title:'Chairman of Council of Ministers',detail:'Stolypin becomes the regime’s dominant minister.'},{id:'1906c',date:'August 1906',title:'Field courts-martial',detail:'Emergency justice accelerates repression.'},{id:'1906d',date:'November 1906',title:'Land decree',detail:'Peasants gain the right to leave the commune.'},{id:'1907',date:'June 1907',title:'Electoral law changed',detail:'The Third Duma is made more conservative.'},{id:'1910',date:'1910',title:'Land reform becomes law',detail:'Consolidation and private ownership receive statutory backing.'},{id:'1911',date:'September 1911',title:'Stolypin assassinated',detail:'He is shot in Kyiv and dies four days later.'},{id:'1914',date:'1914',title:'War interrupts reform',detail:'The countryside remains only partly transformed.'}]};
export const stolypinReformFlashcards=[{id:'stolypin',front:'Peter Stolypin',back:'Prime minister from 1906 to 1911 who combined repression and reform.'},{id:'necktie',front:'Stolypin’s necktie',back:'Nickname for the hangman’s noose used in repression.'},{id:'field',front:'Field courts-martial',back:'Emergency courts used to try and punish suspects rapidly.'},{id:'wager',front:'Wager on the strong',back:'Plan to create prosperous conservative peasant proprietors.'},{id:'mir',front:'Leaving the mir',back:'Withdrawal from communal landholding to establish private property.'},{id:'khutor',front:'Khutor',back:'A consolidated independent farm outside the village.'},{id:'otrub',front:'Otrub',back:'Consolidated private strips while the household remained in the village.'},{id:'bank',front:'Peasant Land Bank',back:'Institution providing loans for peasant land purchase.'},{id:'siberia',front:'Siberian migration',back:'State-supported resettlement to reduce land pressure.'},{id:'coup',front:'June 1907 coup',back:'Unconstitutional alteration of the electoral law.'},{id:'third',front:'Third Duma',back:'More conservative Duma elected under the 1907 law.'},{id:'dual',front:'Repression and reform',back:'Stolypin’s combined strategy for stabilising Tsarism.'}];
export const stolypinReformQuiz=[{id:'q1',question:'When did Stolypin become prime minister?',options:['1906','1894','1905','1911'],correct:'1906'},{id:'q2',question:'What were field courts-martial used for?',options:['Rapid repression','Land surveys','Duma elections','Factory inspection'],correct:'Rapid repression'},{id:'q3',question:'What was Stolypin’s necktie?',options:['The noose','A land law','A railway','A political party'],correct:'The noose'},{id:'q4',question:'What was the wager on the strong?',options:['Creating prosperous peasant proprietors','Arming workers','Expanding the mir','Ending private land'],correct:'Creating prosperous peasant proprietors'},{id:'q5',question:'What could peasants do after the 1906 decree?',options:['Leave the mir','Elect ministers','Abolish taxes','Join the State Council'],correct:'Leave the mir'},{id:'q6',question:'What helped finance land purchase?',options:['Peasant Land Bank','Okhrana','Holy Synod','Soviet'],correct:'Peasant Land Bank'},{id:'q7',question:'What happened in June 1907?',options:['Electoral law changed','October Manifesto issued','Stolypin assassinated','War began'],correct:'Electoral law changed'},{id:'q8',question:'Which Duma was more conservative?',options:['Third Duma','First Duma','Petrograd Soviet','Constituent Assembly'],correct:'Third Duma'},{id:'q9',question:'What limited wider reform?',options:['Conservative resistance and lack of time','Universal support','No rural problems','Complete Duma control'],correct:'Conservative resistance and lack of time'},{id:'q10',question:'Which judgement is strongest?',options:['Stolypin restored order and began reform, but did not resolve structural weakness','He fully transformed Russia','He relied only on reform','He abolished autocracy'],correct:'Stolypin restored order and began reform, but did not resolve structural weakness'}];
export const stolypinReformJudgement={question:'Rank Stolypin’s policies by their contribution to Tsarist stability.',factors:[{id:'repression',title:'Repression',detail:'Executions, exile and police power restored immediate order.'},{id:'land',title:'Land reform',detail:'Private ownership aimed to create loyal peasants.'},{id:'migration',title:'Siberian migration',detail:'Resettlement reduced pressure in some regions.'},{id:'duma',title:'Third Duma cooperation',detail:'A conservative legislature enabled limited lawmaking.'},{id:'coup',title:'Electoral coup',detail:'It reduced opposition but damaged legality.'},{id:'wider',title:'Wider reform plans',detail:'Education and local reform were largely blocked.'}]};
export const stolypinReformAO3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Stolypin gave Tsarism its best chance of long-term survival by creating a conservative peasant class.'},{historian:'Interpretation B',argument:'His achievements were mainly short-term because repression, not reform, restored order.'},{historian:'Interpretation C',argument:'Stolypin failed because Nicholas II and conservative elites would not support the wider changes required.'}]};
export const stolypinReformPeel={question:'“Stolypin was successful in strengthening Tsarism.” Assess the validity of this view.',stretchQuestion:'Plan a thematic answer comparing immediate order, rural reform and political cooperation.',scaffold:['Define success and timeframe.','Use precise evidence on repression.','Assess land reform achievements and limits.','Evaluate the June 1907 change and Third Duma.','Consider Nicholas II and conservative resistance.','Reach a qualified judgement.']};
export const stolypinReformConfidence={prompt:'How confident are you evaluating Stolypin?',leastSecureOptions:['Repression','Land reform','Wager on the strong','Migration','Dumas','June coup','Overall success'],scale:[1,2,3,4,5]};
export const stolypinReformFallbacks:Record<string,any>={lesson_content:{sections:stolypinReformLessonSections},timeline:stolypinReformTimeline,flashcards:{cards:stolypinReformFlashcards},quiz:{questions:stolypinReformQuiz},judgement_ranking:stolypinReformJudgement,ao3_interpretation:stolypinReformAO3,peel_response:stolypinReformPeel,confidence_exit_ticket:stolypinReformConfidence};