export const oppositionBefore1905PathwaySlug='opposition-before-1905';
export const oppositionBefore1905LessonSections=[
{heading:'A changing opposition',body:'By 1905 opposition was broader than under Alexander III. Liberals, Socialist Revolutionaries and Social Democrats challenged autocracy for different reasons and with different methods.',question:'Why did opposition become more diverse?',taskType:'explain'},
{heading:'Liberals',body:'Zemstvo professionals, lawyers and educated elites wanted civil rights, representative institutions and rule of law. Their influence grew through the Union of Liberation, founded in 1903.',question:'What were the strengths and limits of liberalism?',taskType:'judgement'},
{heading:'Socialist Revolutionaries',body:'The SRs, formed in 1901, drew on populism and appealed to peasants through demands for land socialisation. Their Combat Organisation used political assassination.',question:'Why could the SRs appeal beyond the cities?',taskType:'explain'},
{heading:'Social Democrats',body:'The Russian Social Democratic Labour Party, founded in 1898, applied Marxism to Russia and focused on the industrial working class.',question:'Why did Marxists see workers as revolutionary?',taskType:'explain'},
{heading:'The 1903 split',body:'At the Second Party Congress, Bolsheviks and Mensheviks divided over organisation and revolutionary strategy. Lenin favoured a disciplined vanguard party; Mensheviks envisaged a broader movement.',question:'How serious was the split?',taskType:'comparison'},
{heading:'Lenin',body:'Lenin argued that workers needed professional revolutionaries to develop political consciousness and overthrow autocracy. His ideas increased organisational focus but narrowed the party.',question:'How important was Lenin before 1905?',taskType:'judgement'},
{heading:'Workers',body:'Strikes, poor conditions and factory concentration gave revolutionaries an audience, although many workers pursued immediate economic rather than ideological goals.',question:'How far were workers revolutionary?',taskType:'judgement'},
{heading:'Peasants',body:'Land hunger and rural poverty generated unrest, but low literacy, dispersed settlement and loyalty to the Tsar limited sustained political organisation.',question:'Why was peasant discontent difficult to mobilise?',taskType:'explain'},
{heading:'State repression',body:'The Okhrana infiltrated parties, censored publications and exiled activists. Repression disrupted organisation but could radicalise opponents and expose the regime’s inflexibility.',question:'Did repression strengthen or weaken Tsarism?',taskType:'comparison'},
{heading:'Overall seriousness',body:'Before 1905 opposition remained divided, illegal and socially fragmented. Yet it had clearer organisations, stronger ideas and greater access to workers and educated society than in 1894.',question:'How serious was opposition by 1905?',taskType:'judgement'}];
export const oppositionBefore1905Timeline={events:[{id:'1898',date:'1898',title:'RSDLP founded',detail:'Marxists establish a national party.'},{id:'1901',date:'1901',title:'SR Party formed',detail:'Populist and socialist currents unite.'},{id:'1902',date:'1902',title:'Plehve appointed',detail:'Repression of opposition intensifies.'},{id:'1903a',date:'1903',title:'Union of Liberation formed',detail:'Liberals coordinate demands for constitutional reform.'},{id:'1903b',date:'1903',title:'Bolshevik-Menshevik split',detail:'Social Democrats divide over organisation and strategy.'},{id:'1904',date:'1904',title:'Plehve assassinated',detail:'The SR Combat Organisation demonstrates terrorist capacity.'},{id:'1904z',date:'1904',title:'Zemstvo congress',detail:'Liberals press publicly for reform.'},{id:'1905',date:'1905',title:'Opposition enters mass revolution',detail:'Parties interact with strikes, soviets and peasant unrest.'}]};
export const oppositionBefore1905Flashcards=[{id:'liberal',front:'Liberals',back:'Opponents seeking civil rights, law and representative government.'},{id:'uol',front:'Union of Liberation',back:'Liberal organisation founded in 1903.'},{id:'sr',front:'Socialist Revolutionaries',back:'Party combining populist socialism, peasant appeal and terrorism.'},{id:'land',front:'Land socialisation',back:'Transfer of land for communal use rather than private landlord ownership.'},{id:'combat',front:'Combat Organisation',back:'SR terrorist wing responsible for assassinations.'},{id:'rsdlp',front:'RSDLP',back:'Marxist Russian Social Democratic Labour Party.'},{id:'bolshevik',front:'Bolsheviks',back:'Lenin’s disciplined revolutionary faction.'},{id:'menshevik',front:'Mensheviks',back:'Faction favouring a broader party and longer bourgeois stage.'},{id:'vanguard',front:'Vanguard party',back:'A tightly organised party of professional revolutionaries.'},{id:'okhrana',front:'Okhrana',back:'Tsarist secret police.'},{id:'economic',front:'Economic protest',back:'Action focused on wages, hours and conditions.'},{id:'political',front:'Political protest',back:'Action directed against the state or autocracy.'}];
export const oppositionBefore1905Quiz=[{id:'q1',question:'Which group wanted representative government?',options:['Liberals','Black Hundreds','Land Captains','Holy Synod'],correct:'Liberals'},{id:'q2',question:'Which party appealed most directly to peasants?',options:['SRs','Bolsheviks','Octobrists','Kadets'],correct:'SRs'},{id:'q3',question:'What was the SR terrorist wing?',options:['Combat Organisation','Soviet','Duma','Zubatov union'],correct:'Combat Organisation'},{id:'q4',question:'When was the RSDLP founded?',options:['1898','1881','1905','1912'],correct:'1898'},{id:'q5',question:'What happened in 1903?',options:['Bolshevik-Menshevik split','October Manifesto','Stolypin coup','February Revolution'],correct:'Bolshevik-Menshevik split'},{id:'q6',question:'Who favoured a disciplined vanguard?',options:['Lenin','Plehve','Witte','Gapon'],correct:'Lenin'},{id:'q7',question:'Why were workers easier to organise than peasants?',options:['They were concentrated in factories','They owned more land','They faced no repression','They all supported Marxism'],correct:'They were concentrated in factories'},{id:'q8',question:'What limited peasant organisation?',options:['Dispersal and low literacy','Too many national elections','Strong trade unions','High urban concentration'],correct:'Dispersal and low literacy'},{id:'q9',question:'What was the Okhrana?',options:['Secret police','Liberal newspaper','Workers council','Peasant commune'],correct:'Secret police'},{id:'q10',question:'Which judgement is strongest?',options:['Opposition was divided but more organised and socially connected than in 1894','Opposition was united','Opposition already controlled the state','There was no serious opposition'],correct:'Opposition was divided but more organised and socially connected than in 1894'}];
export const oppositionBefore1905Judgement={question:'Rank the opposition groups by threat to Tsarism before 1905.',factors:[{id:'liberals',title:'Liberals',detail:'Respectable networks and constitutional demands.'},{id:'srs',title:'SRs',detail:'Peasant appeal and political terrorism.'},{id:'bolsheviks',title:'Bolsheviks',detail:'Disciplined revolutionary organisation.'},{id:'mensheviks',title:'Mensheviks',detail:'Broader socialist organisation among workers.'},{id:'workers',title:'Workers',detail:'Strike capacity in concentrated industries.'},{id:'peasants',title:'Peasants',detail:'Mass grievance but weak coordination.'}]};
export const oppositionBefore1905AO3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Liberals posed the most credible challenge because they connected elite criticism to constitutional reform.'},{historian:'Interpretation B',argument:'The SRs were the greatest immediate threat because terrorism exposed the state’s vulnerability.'},{historian:'Interpretation C',argument:'Opposition remained weak before 1905 because ideological division prevented a united movement.'}]};
export const oppositionBefore1905Peel={question:'“Opposition posed a serious threat to Tsarism before 1905.” Assess the validity of this view.',stretchQuestion:'Plan a thematic essay comparing organisation, social reach, methods and state response.',scaffold:['Define serious threat.','Compare liberals, SRs and Social Democrats.','Use evidence on workers and peasants.','Assess division and repression.','Reach a qualified judgement.']};
export const oppositionBefore1905Confidence={prompt:'How confident are you comparing opposition before 1905?',leastSecureOptions:['Liberals','SRs','Social Democrats','1903 split','Workers','Peasants','Repression'],scale:[1,2,3,4,5]};
export const oppositionBefore1905Fallbacks:Record<string,any>={lesson_content:{sections:oppositionBefore1905LessonSections},timeline:oppositionBefore1905Timeline,flashcards:{cards:oppositionBefore1905Flashcards},quiz:{questions:oppositionBefore1905Quiz},judgement_ranking:oppositionBefore1905Judgement,ao3_interpretation:oppositionBefore1905AO3,peel_response:oppositionBefore1905Peel,confidence_exit_ticket:oppositionBefore1905Confidence};