type Section={heading:string;body:string;question:string;taskType:string};
type Event={id:string;date:string;title:string;detail:string};
type LessonSeed={slug:string;sections:Section[];events:Event[];terms:[string,string][];quiz:[string,string][];judgementQuestion:string;factors:string[];interpretations:string[];essayQuestion:string;stretch:string;confidence:string[]};

function buildLesson(seed:LessonSeed){
 const cards=seed.terms.map((x,i)=>({id:`f${i+1}`,front:x[0],back:x[1]}));
 const distractors=['Operation Barbarossa','The Great Terror','The Five-Year Plans','De-Stalinisation'];
 const questions=seed.quiz.map((x,i)=>({id:`q${i+1}`,question:x[0],options:[x[1],...distractors.filter(y=>y!==x[1]).slice(0,3)],correct:x[1]}));
 return {slug:seed.slug,fallbacks:{lesson_content:{sections:seed.sections},timeline:{events:seed.events},flashcards:{cards},quiz:{questions},judgement_ranking:{question:seed.judgementQuestion,factors:seed.factors.map((title,i)=>({id:`j${i+1}`,title,detail:'Rank this factor and support it with precise evidence.'}))},ao3_interpretation:{question:'Evaluate each interpretation separately using relevant contextual knowledge.',interpretations:seed.interpretations.map((argument,i)=>({historian:`Interpretation ${String.fromCharCode(65+i)}`,argument}))},peel_response:{question:seed.essayQuestion,stretchQuestion:seed.stretch,scaffold:['Define the key judgement in the question.','Develop two or three supported factors.','Compare relative importance and limits.','Reach a sustained overall judgement.']},confidence_exit_ticket:{prompt:`How confident are you with ${seed.slug.replaceAll('-',' ')}?`,leastSecureOptions:seed.confidence,scale:[1,2,3,4,5]}}};
}

export const barbarossaLeadershipLesson=buildLesson({slug:'barbarossa-stalin-leadership',sections:[
{heading:'The shock of invasion',body:'Germany invaded the USSR on 22 June 1941. Stalin had ignored or discounted repeated warnings, and the Red Army suffered catastrophic losses of men, aircraft and territory.',question:'How responsible was Stalin for the initial disaster?',taskType:'judgement'},
{heading:'Stalin recovers control',body:'After a brief withdrawal Stalin addressed the population, became Supreme Commander and concentrated military, political and economic authority through the State Defence Committee.',question:'Why did Stalin remain in power?',taskType:'explain'},
{heading:'Command and interference',body:'Stalin initially imposed unrealistic orders and resisted retreats. Over time he listened more closely to commanders such as Zhukov and allowed greater operational professionalism.',question:'Did Stalin become an effective war leader?',taskType:'comparison'},
{heading:'The patriotic war',body:'The regime presented the conflict as a Great Patriotic War, drawing on Russian history, defence of the motherland and hatred of Nazi occupation as well as Communist ideology.',question:'Why did patriotism matter?',taskType:'explain'},
{heading:'Overall judgement',body:'Stalin contributed heavily to the disasters of 1941 but later supplied central direction, political resolve and coordination. Soviet victory cannot be explained by leadership alone.',question:'How far did Stalin contribute to victory?',taskType:'judgement'}],events:[{id:'inv',date:'22 Jun 1941',title:'Operation Barbarossa',detail:'Germany launches its invasion of the USSR.'},{id:'gko',date:'30 Jun 1941',title:'State Defence Committee',detail:'Emergency authority is concentrated under Stalin.'},{id:'moscow',date:'Dec 1941',title:'Moscow counter-offensive',detail:'The German advance is halted.'},{id:'stalingrad',date:'Feb 1943',title:'Victory at Stalingrad',detail:'A decisive German army surrenders.'},{id:'berlin',date:'May 1945',title:'Victory in Europe',detail:'The Red Army captures Berlin.'}],terms:[['Operation Barbarossa','German invasion of the USSR in June 1941.'],['State Defence Committee','Emergency body directing the Soviet war effort.'],['Supreme Commander','Stalin’s role as head of the armed forces.'],['Great Patriotic War','Soviet patriotic name for the war against Nazi Germany.'],['Zhukov','Leading Soviet marshal associated with major victories.'],['Scorched earth','Destruction of resources to deny them to the enemy.']],quiz:[['When did Germany invade the USSR?','22 June 1941'],['What emergency body directed the war?','State Defence Committee'],['Who became Supreme Commander?','Stalin'],['Which marshal became especially prominent?','Zhukov'],['What name framed the conflict patriotically?','Great Patriotic War'],['Which battle ended in February 1943?','Stalingrad']],judgementQuestion:'Rank the factors explaining Stalin’s wartime leadership.',factors:['Pre-war misjudgement','Centralised authority','Learning from generals','Patriotic mobilisation','Military commanders','Soviet resources'],interpretations:['Stalin’s errors made the catastrophe of 1941 far worse.','Stalin developed into a formidable and effective wartime leader.','Victory resulted principally from institutions and society rather than Stalin personally.'],essayQuestion:'“Stalin’s leadership was the main reason the Soviet Union survived and won the war.” Assess the validity of this view.',stretch:'Separate Stalin’s contribution in 1941 from his role after the turning point.',confidence:['Barbarossa','Initial defeats','State Defence Committee','Commanders','Patriotism','Overall judgement']});

export const wartimeControlLesson=buildLesson({slug:'wartime-politics-opposition-nationalities',sections:[
{heading:'Party and government',body:'Normal Party congresses and collective procedures declined during wartime. Decision-making centred on Stalin, the State Defence Committee and a small group of senior officials.',question:'How did war alter government?',taskType:'comparison'},
{heading:'Control and discipline',body:'The NKVD enforced labour discipline, guarded strategic sites and punished defeatism, desertion and alleged collaboration. Order No. 227 demanded “Not one step back”.',question:'How important was coercion?',taskType:'judgement'},
{heading:'Collaboration and opposition',body:'Some Soviet citizens served German forces or administrations for reasons ranging from anti-Stalinism and nationalism to survival. The regime treated collaboration as treason.',question:'Why did collaboration occur?',taskType:'explain'},
{heading:'Nationalities',body:'Several national groups, including Chechens, Crimean Tatars and Volga Germans, were collectively deported on accusations of disloyalty. Other national identities were mobilised for war.',question:'Did war strengthen Soviet unity?',taskType:'judgement'},
{heading:'Continuity and change',body:'The wartime state relaxed selected ideological controls while preserving dictatorship. Central authority, surveillance and collective punishment remained fundamental.',question:'How far did political authority change?',taskType:'judgement'}],events:[{id:'order',date:'Jul 1942',title:'Order No. 227',detail:'Retreat without authorisation is severely punished.'},{id:'comm',date:'1942–45',title:'Collaboration',detail:'Soviet citizens serve German military and civil structures.'},{id:'chechen',date:'1944',title:'Chechen and Ingush deportation',detail:'Entire populations are transported east.'},{id:'crimea',date:'May 1944',title:'Crimean Tatars deported',detail:'Collective punishment follows Soviet reconquest.'}],terms:[['Order No. 227','1942 order demanding no unauthorised retreat.'],['Blocking detachment','Unit used to prevent panic or desertion.'],['Hilfswillige','Soviet citizens serving German forces in auxiliary roles.'],['Collaboration','Cooperation with the occupying enemy.'],['Deportation','Forced mass removal of a population.'],['Collective punishment','Punishment applied to a whole group for alleged disloyalty.']],quiz:[['What did Order No. 227 demand?','Not one step back'],['Which body enforced internal security?','NKVD'],['Who were Hilfswillige?','Soviet auxiliaries for Germany'],['Which people were deported from Crimea?','Crimean Tatars'],['What happened to normal Party procedure?','It declined'],['What remained central?','Dictatorship']],judgementQuestion:'Rank the methods used to preserve wartime political control.',factors:['Stalin’s authority','State Defence Committee','NKVD coercion','Patriotic mobilisation','Collective punishment','Party administration'],interpretations:['War intensified Stalinist coercion and centralisation.','Patriotism and voluntary commitment mattered more than repression.','The nationalities policy exposed the weakness of claims to Soviet unity.'],essayQuestion:'“Coercion was the most important means of maintaining Soviet political control during the war.” Assess the validity of this view.',stretch:'Compare formal state power with popular consent and patriotism.',confidence:['Government','Order 227','NKVD','Collaboration','Nationalities','Continuity']});

export const wartimeEconomyLesson=buildLesson({slug:'wartime-economy-mobilisation',sections:[
{heading:'Evacuation of industry',body:'Factories, machinery and workers were moved east of the Urals during 1941. The operation was chaotic but preserved a large part of Soviet industrial capacity.',question:'Why was evacuation decisive?',taskType:'judgement'},
{heading:'Command mobilisation',body:'Planning agencies redirected output towards tanks, aircraft, artillery and ammunition. Standardisation and concentration on a limited range of weapons raised production.',question:'How effective was central planning?',taskType:'judgement'},
{heading:'Labour and sacrifice',body:'Long hours, strict discipline, rationing and the mobilisation of women, teenagers and Gulag prisoners sustained production. Living standards fell sharply.',question:'Who bore the cost of mobilisation?',taskType:'explain'},
{heading:'Agriculture and supply',body:'Occupation removed fertile land and millions of workers and animals. Collective farms struggled to supply the army and cities, while hunger remained widespread.',question:'Why was agriculture vulnerable?',taskType:'explain'},
{heading:'Allied aid and achievement',body:'Lend-Lease supplied vehicles, food, raw materials and communications equipment. Soviet production remained central, but Allied support improved mobility and logistics.',question:'How important was Lend-Lease?',taskType:'comparison'}],events:[{id:'evac',date:'1941',title:'Industrial evacuation',detail:'Factories and workers move eastward.'},{id:'recovery',date:'1942',title:'War production recovers',detail:'Eastern plants expand military output.'},{id:'lease',date:'1941–45',title:'Lend-Lease deliveries',detail:'Allies provide transport, food and materials.'},{id:'peak',date:'1943–44',title:'Soviet production peaks',detail:'Mass output supports advancing armies.'}],terms:[['Evacuation','Removal of industry and workers from threatened western regions.'],['War economy','Economy directed overwhelmingly towards military needs.'],['Lend-Lease','Allied supply programme providing equipment and materials.'],['Standardisation','Producing fewer, simpler weapon models in large numbers.'],['Rationing','State-controlled allocation of scarce food and goods.'],['Mobilisation','Organisation of people and resources for total war.']],quiz:[['Where was much industry moved?','East of the Urals'],['What received production priority?','Weapons'],['Who entered industry in greater numbers?','Women'],['What Allied programme supplied the USSR?','Lend-Lease'],['What happened to living standards?','They fell'],['What improved weapon output?','Standardisation']],judgementQuestion:'Rank the reasons for Soviet economic success in wartime.',factors:['Industrial evacuation','Central planning','Worker sacrifice','Pre-war industrialisation','Lend-Lease','German weaknesses'],interpretations:['Pre-war industrialisation made wartime victory possible.','The evacuation and reconstruction of industry was the decisive achievement.','Allied aid was indispensable to Soviet mobility and supply.'],essayQuestion:'“The evacuation of industry was the main reason for Soviet economic success during the war.” Assess the validity of this view.',stretch:'Judge production, logistics, food supply and human cost separately.',confidence:['Evacuation','Planning','Labour','Agriculture','Lend-Lease','Success']});

export const wartimeSocietyLesson=buildLesson({slug:'soviet-society-at-war',sections:[
{heading:'Human loss and occupation',body:'The USSR suffered enormous military and civilian casualties. Occupation brought mass murder, forced labour, starvation and destruction across western regions.',question:'How did occupation shape Soviet experience?',taskType:'explain'},
{heading:'Workers and peasants',body:'Urban workers endured long shifts and rationing; peasants faced requisitioning, labour shortages and devastation. Informal exchange and private plots remained vital.',question:'Whose burden was greatest?',taskType:'judgement'},
{heading:'Women and family',body:'Women served in industry, medicine, agriculture, partisan units and the armed forces. Their contribution expanded, though traditional expectations and family burdens persisted.',question:'Did war transform women’s status?',taskType:'comparison'},
{heading:'Religion and culture',body:'The state revived patriotic history and eased persecution of the Orthodox Church. In 1943 Stalin permitted the restoration of the Patriarchate to strengthen unity.',question:'Why did Stalin relax religious policy?',taskType:'explain'},
{heading:'Partisans and morale',body:'Partisans disrupted German communications and represented active resistance, although their relationship with local communities could be difficult. Propaganda celebrated sacrifice and revenge.',question:'What sustained morale?',taskType:'judgement'}],events:[{id:'siege',date:'1941–44',title:'Siege of Leningrad',detail:'Mass starvation and bombardment kill civilians.'},{id:'women',date:'1941–45',title:'Women mobilised',detail:'Women expand their roles in production and combat support.'},{id:'church',date:'1943',title:'Patriarchate restored',detail:'The Orthodox hierarchy receives limited recognition.'},{id:'liberation',date:'1943–45',title:'Occupied territories liberated',detail:'Communities confront destruction and collaboration accusations.'}],terms:[['Siege of Leningrad','German encirclement causing extreme civilian suffering.'],['Partisan','Irregular fighter operating behind enemy lines.'],['Patriarchate','Central leadership institution of the Orthodox Church.'],['Occupation','Enemy control of Soviet territory.'],['Private plot','Small area farmed individually by collective farmers.'],['Total war','Conflict mobilising the whole economy and population.']],quiz:[['Which city endured a prolonged siege?','Leningrad'],['Who fought behind German lines?','Partisans'],['What Church body returned in 1943?','Patriarchate'],['What happened to women’s employment?','It expanded'],['What helped peasants survive?','Private plots'],['What characterised civilian life?','Severe sacrifice']],judgementQuestion:'Rank the most significant effects of war on Soviet society.',factors:['Mass casualties','Occupation','Women’s roles','Worker conditions','Religious relaxation','Patriotic unity'],interpretations:['War generated genuine social unity around defence of the motherland.','The burdens of war deepened inequalities and suffering within Soviet society.','Temporary religious and cultural concessions did not end Stalinist control.'],essayQuestion:'“The war produced more social change than continuity in the Soviet Union.” Assess the validity of this view.',stretch:'Compare women, workers, peasants, believers and occupied populations.',confidence:['Casualties','Occupation','Workers','Women','Religion','Partisans']});

export const impactVictoryLesson=buildLesson({slug:'victory-impact-1945',sections:[
{heading:'Scale of victory',body:'The defeat of Nazi Germany transformed the USSR into a superpower with military control across Eastern Europe. Victory greatly enhanced Stalin’s international and domestic prestige.',question:'Why did victory strengthen Stalin?',taskType:'explain'},
{heading:'Human and material cost',body:'Tens of millions were dead, disabled or displaced. Cities, villages, farms and infrastructure across western USSR had been devastated.',question:'How far did victory conceal catastrophe?',taskType:'judgement'},
{heading:'Returning soldiers and civilians',body:'Demobilised troops, former prisoners of war and forced labourers returned to suspicion and screening. Exposure to Europe encouraged official fears of ideological contamination.',question:'Why did returnees face suspicion?',taskType:'explain'},
{heading:'Stalin and government',body:'Stalin emerged more prestigious but also more suspicious and distant. Wartime collective structures did not develop into political liberalisation after 1945.',question:'Did war change Stalin’s governing style?',taskType:'comparison'},
{heading:'The people and expectations',body:'Many citizens hoped wartime sacrifice would bring improved living conditions and relaxation. Instead reconstruction, scarcity and renewed discipline dominated the immediate post-war years.',question:'Why were expectations disappointed?',taskType:'judgement'}],events:[{id:'victory',date:'May 1945',title:'Victory over Germany',detail:'The USSR emerges victorious and occupies Eastern Europe.'},{id:'parade',date:'Jun 1945',title:'Victory Parade',detail:'Military triumph is celebrated in Moscow.'},{id:'demob',date:'1945–48',title:'Demobilisation',detail:'Millions of service personnel return to civilian life.'},{id:'famine',date:'1946–47',title:'Post-war famine',detail:'Drought, requisitioning and disruption produce severe hunger.'}],terms:[['Superpower','State possessing exceptional military and international influence.'],['Demobilisation','Return of military personnel to civilian life.'],['Repatriation','Return of displaced citizens and prisoners.'],['Filtration','Security screening of returning Soviet citizens.'],['Reconstruction','Rebuilding the economy and damaged regions.'],['Ideological contamination','Official fear that foreign contact weakened loyalty.']],quiz:[['What status did the USSR gain after victory?','Superpower'],['Who faced security screening?','Returnees'],['What did many citizens expect?','Relaxation'],['What followed the war economically?','Reconstruction'],['When did a major famine occur?','1946–47'],['What happened to Stalin’s prestige?','It increased']],judgementQuestion:'Rank the most important consequences of Soviet victory.',factors:['Stalin’s prestige','Superpower status','Human loss','Economic destruction','Public expectations','Renewed suspicion'],interpretations:['Victory represented the high point of Stalin’s personal legitimacy.','The scale of destruction limited the practical benefits of victory.','War changed Soviet international power more than its domestic political system.'],essayQuestion:'“The most important effect of the Second World War was the strengthening of Stalin’s authority.” Assess the validity of this view.',stretch:'Compare political, economic, social and international consequences.',confidence:['Victory','Losses','Returnees','Government','Expectations','Superpower']});

export const highStalinismLesson=buildLesson({slug:'high-stalinism-1945-53',sections:[
{heading:'Return to ideological discipline',body:'After 1945 the regime rejected hopes of relaxation. Zhdanov promoted strict cultural conformity, attacks on western influence and renewed supervision of writers, artists and scientists.',question:'Why did ideological control revive?',taskType:'explain'},
{heading:'Political insecurity',body:'Stalin weakened potential rivals and increasingly governed through a narrow personal circle. The Leningrad Affair destroyed prominent officials associated with the wartime city leadership.',question:'How did Stalin manage the elite?',taskType:'judgement'},
{heading:'Campaigns and persecution',body:'The regime pursued alleged cosmopolitans, nationalists and spies. Anti-Jewish measures intensified, culminating in the Doctors’ Plot of 1952–53.',question:'What explains renewed persecution?',taskType:'judgement'},
{heading:'Economy and society',body:'The Fourth Five-Year Plan restored heavy industry rapidly, but agriculture, housing and consumer goods remained weak. The famine of 1946–47 exposed continuing hardship.',question:'How successful was reconstruction?',taskType:'comparison'},
{heading:'Death and power vacuum',body:'Stalin died in March 1953 before the Doctors’ Plot could develop further. His death exposed the absence of an agreed successor and the dangers created by personal dictatorship.',question:'What was Stalin’s final legacy?',taskType:'judgement'}],events:[{id:'zhdanov',date:'1946',title:'Zhdanovshchina',detail:'Cultural and ideological controls intensify.'},{id:'len',date:'1949–50',title:'Leningrad Affair',detail:'Senior Party officials are removed and executed.'},{id:'anti',date:'1948–53',title:'Anti-cosmopolitan campaign',detail:'Intellectuals, especially Jews, face persecution.'},{id:'doctors',date:'1952–53',title:'Doctors’ Plot',detail:'Doctors are accused of murdering Soviet leaders.'},{id:'death',date:'5 Mar 1953',title:'Stalin dies',detail:'A leadership struggle begins.'}],terms:[['High Stalinism','Term for intensified control and orthodoxy after 1945.'],['Zhdanovshchina','Post-war campaign enforcing cultural conformity.'],['Leningrad Affair','Purge of officials linked to Leningrad.'],['Rootless cosmopolitan','Code used in campaigns against allegedly westernised intellectuals.'],['Doctors’ Plot','Fabricated conspiracy allegation against mainly Jewish doctors.'],['Fourth Five-Year Plan','Post-war reconstruction plan beginning in 1946.']],quiz:[['Who led the cultural campaign?','Zhdanov'],['Which city’s officials were purged?','Leningrad'],['What was targeted before Stalin’s death?','Doctors’ Plot'],['What remained the economic priority?','Heavy industry'],['When did Stalin die?','1953'],['What followed his death?','Power vacuum']],judgementQuestion:'Rank the defining features of High Stalinism.',factors:['Stalin’s personal dominance','Cultural repression','Elite purges','Anti-Jewish campaigns','Industrial reconstruction','Consumer hardship'],interpretations:['The final Stalin years were a straightforward return to pre-war terror.','Post-war repression reflected Stalin’s growing paranoia and fear of foreign influence.','Reconstruction and superpower status coexisted with a brittle political system.'],essayQuestion:'“Stalin’s main concern after 1945 was the destruction of political opposition.” Assess the validity of this view.',stretch:'Compare elite security, ideology, foreign influence and economic reconstruction.',confidence:['Zhdanovshchina','Leningrad Affair','Anti-cosmopolitanism','Doctors’ Plot','Reconstruction','Legacy']});

export const unit8Lessons=[barbarossaLeadershipLesson,wartimeControlLesson,wartimeEconomyLesson,wartimeSocietyLesson,impactVictoryLesson,highStalinismLesson];
