export const nicholasIIRulerPathwaySlug='nicholas-ii-ruler';
export const nicholasIIRulerLessonSections=[
{heading:'The new Tsar',body:'Nicholas II became Tsar in 1894 aged twenty-six. He inherited intact autocratic institutions but also rural poverty, industrial change and emerging opposition. His significance lies in how he used—or failed to use—the powers he possessed.',question:'What did Nicholas inherit in 1894?',taskType:'explain'},
{heading:'Belief in autocracy',body:'Nicholas regarded autocracy as a sacred duty inherited from his father. He rejected representative government and described constitutional aspirations as senseless dreams in 1895.',question:'How did ideology restrict political adaptation?',taskType:'judgement'},
{heading:'Personality and preparation',body:'Nicholas was conscientious in routine work but indecisive, conflict-averse and poorly prepared for supreme rule. He often postponed decisions and relied on a narrow family circle.',question:'Which weaknesses mattered most in an autocracy?',taskType:'judgement'},
{heading:'Decision making',body:'Ministers served the Tsar separately rather than through a united cabinet. Nicholas encouraged rivalry between officials and frequently reversed decisions, weakening coordination.',question:'Why did personal government create administrative weakness?',taskType:'explain'},
{heading:'Alexandra and the court',body:'Nicholas relied heavily on Empress Alexandra and distrusted public opinion. Court isolation reinforced his belief that criticism came from disloyal elites rather than genuine social pressures.',question:'How did isolation shape political judgement?',taskType:'judgement'},
{heading:'Khodynka, 1896',body:'More than a thousand people died in a crush during coronation celebrations. Nicholas attended a French embassy ball that evening, creating an early impression of distance from popular suffering.',question:'Why did symbolism matter to monarchy?',taskType:'explain'},
{heading:'Continuity with Alexander III',body:'Nicholas retained censorship, police surveillance, Russification and restrictions on zemstva. Yet he lacked his father’s authority and decisiveness.',question:'Was continuity a source of strength or weakness?',taskType:'comparison'},
{heading:'Ministers and alternatives',body:'Witte promoted economic modernisation while Plehve favoured repression. Nicholas failed to reconcile these strategies into a coherent programme.',question:'How far was policy inconsistency the Tsar’s responsibility?',taskType:'judgement'},
{heading:'Structural pressures',body:'No ruler controlled all circumstances. Population growth, land hunger, rapid urbanisation and new political movements created pressures that would have challenged any autocrat.',question:'How should individual and structural causes be balanced?',taskType:'comparison'},
{heading:'Overall judgement',body:'Nicholas did not create every weakness, but his rigid beliefs, indecision and poor political judgement reduced the regime’s ability to adapt. In a personal autocracy, shortcomings at the centre had unusually large consequences.',question:'How far was Nicholas responsible for weakening autocracy?',taskType:'judgement'}];
export const nicholasIIRulerTimeline={events:[{id:'1894',date:'1894',title:'Nicholas II becomes Tsar',detail:'He inherits autocratic power and growing social pressures.'},{id:'1895',date:'1895',title:'Senseless dreams speech',detail:'Nicholas rejects representative aspirations.'},{id:'1896',date:'1896',title:'Khodynka disaster',detail:'The coronation tragedy damages his public image.'},{id:'1899',date:'1899',title:'Student unrest',detail:'Educational discontent highlights political tension.'},{id:'1901',date:'1901',title:'SR Party formed',detail:'Revolutionary opposition becomes more organised.'},{id:'1903',date:'1903',title:'Social Democrats split',detail:'Bolsheviks and Mensheviks emerge.'},{id:'1904',date:'1904',title:'War with Japan',detail:'Nicholas approves a risky conflict.'},{id:'1905',date:'1905',title:'Revolution',detail:'The regime faces its first nationwide political crisis.'}]};
export const nicholasIIRulerFlashcards=[{id:'autocracy',front:'Autocracy',back:'Government in which the Tsar held unrestricted sovereign authority.'},{id:'divine',front:'Sacred duty',back:'Nicholas believed autocracy was entrusted to him by God.'},{id:'senseless',front:'Senseless dreams',back:'Nicholas’s 1895 dismissal of representative aspirations.'},{id:'indecision',front:'Indecision',back:'Delay, reversal or avoidance of difficult political choices.'},{id:'court',front:'Court isolation',back:'Dependence on family and courtiers rather than wider opinion.'},{id:'khodynka',front:'Khodynka',back:'The 1896 coronation crowd disaster.'},{id:'ministerial',front:'Ministerial rivalry',back:'Competition between officials encouraged by the absence of collective government.'},{id:'witte',front:'Witte',back:'Finance Minister associated with state-led industrialisation.'},{id:'plehve',front:'Plehve',back:'Interior Minister associated with repression and Russification.'},{id:'structural',front:'Structural pressure',back:'A long-term problem not created by one individual.'},{id:'adaptation',front:'Political adaptation',back:'Changing institutions or policy to absorb pressure.'},{id:'personal',front:'Personal autocracy',back:'A system in which the ruler’s qualities directly shape government.'}];
export const nicholasIIRulerQuiz=[{id:'q1',question:'When did Nicholas II become Tsar?',options:['1894','1881','1905','1914'],correct:'1894'},{id:'q2',question:'What did Nicholas call representative aspirations?',options:['Senseless dreams','Necessary reform','Popular sovereignty','A sacred duty'],correct:'Senseless dreams'},{id:'q3',question:'What happened at Khodynka?',options:['A crowd disaster','A military victory','A Duma election','A peasant reform'],correct:'A crowd disaster'},{id:'q4',question:'Which trait weakened decision making?',options:['Indecision','Federalism','Republicanism','Military expertise'],correct:'Indecision'},{id:'q5',question:'Who promoted industrial modernisation?',options:['Witte','Plehve','Gapon','Trotsky'],correct:'Witte'},{id:'q6',question:'Who favoured repression?',options:['Plehve','Witte','Milyukov','Kerensky'],correct:'Plehve'},{id:'q7',question:'Why did ministerial rivalry matter?',options:['It reduced coordination','It created parliament','It ended censorship','It strengthened parties'],correct:'It reduced coordination'},{id:'q8',question:'What did Nicholas inherit?',options:['Autocracy and unresolved pressures','A republic','A stable parliament','Universal suffrage'],correct:'Autocracy and unresolved pressures'},{id:'q9',question:'Why did personality matter greatly?',options:['The system concentrated power in the ruler','The Tsar had no power','Ministers were elected','Courts controlled policy'],correct:'The system concentrated power in the ruler'},{id:'q10',question:'Which judgement is strongest?',options:['Nicholas magnified inherited weaknesses through rigid and ineffective leadership','Nicholas alone created every problem','Nicholas had no influence','Autocracy was already abolished'],correct:'Nicholas magnified inherited weaknesses through rigid and ineffective leadership'}];
export const nicholasIIRulerJudgement={question:'Rank the features of Nicholas II’s leadership that most weakened autocracy.',factors:[{id:'beliefs',title:'Rigid autocratic beliefs',detail:'He rejected meaningful political participation.'},{id:'indecision',title:'Indecision',detail:'He delayed and reversed important choices.'},{id:'isolation',title:'Court isolation',detail:'He distrusted wider opinion.'},{id:'coordination',title:'Poor coordination',detail:'Ministers pursued competing strategies.'},{id:'symbolism',title:'Public symbolism',detail:'Khodynka damaged monarchical legitimacy.'},{id:'structures',title:'Inherited pressures',detail:'Land, industry and opposition limited his freedom of action.'}]};
export const nicholasIIRulerAO3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'Nicholas II’s rigid commitment to autocracy was the central reason the regime failed to adapt.'},{historian:'Interpretation B',argument:'His personality mattered less than the immense social and economic pressures inherited in 1894.'},{historian:'Interpretation C',argument:'Nicholas weakened Tsarism chiefly because personal rule turned private indecision into state paralysis.'}]};
export const nicholasIIRulerPeel={question:'“Nicholas II was primarily responsible for the weakness of autocracy by 1905.” Assess the validity of this view.',stretchQuestion:'Write an introduction and one comparative paragraph balancing leadership against inherited pressures.',scaffold:['Define responsibility.','Use precise evidence about beliefs and decisions.','Assess ministerial and structural factors.','Explain why personal weaknesses mattered more in an autocracy.','Reach a qualified judgement.']};
export const nicholasIIRulerConfidence={prompt:'How confident are you judging Nicholas II as ruler?',leastSecureOptions:['Beliefs','Personality','Decision making','Court influence','Ministers','Inherited pressures'],scale:[1,2,3,4,5]};
export const nicholasIIRulerFallbacks:Record<string,any>={lesson_content:{sections:nicholasIIRulerLessonSections},timeline:nicholasIIRulerTimeline,flashcards:{cards:nicholasIIRulerFlashcards},quiz:{questions:nicholasIIRulerQuiz},judgement_ranking:nicholasIIRulerJudgement,ao3_interpretation:nicholasIIRulerAO3,peel_response:nicholasIIRulerPeel,confidence_exit_ticket:nicholasIIRulerConfidence};