export const manifestoFundamentalLawsPathwaySlug='manifesto-fundamental-laws';
export const manifestoFundamentalLawsLessonSections=[
{heading:'The October crisis',body:'By autumn 1905 strikes, peasant unrest, mutiny and the St Petersburg Soviet created a nationwide crisis. The regime needed either major concessions or large-scale repression.',question:'Why was October 1905 a decisive moment?',taskType:'explain'},
{heading:'The October Manifesto',body:'Issued on 17 October 1905, the Manifesto promised civil liberties, a wider franchise and that no law would take effect without Duma approval.',question:'What appeared to change?',taskType:'explain'},
{heading:'Witte’s role',body:'Witte persuaded Nicholas that concession was necessary to divide moderate liberals from revolutionaries. Nicholas accepted reluctantly and later resented the compromise.',question:'How important was Witte?',taskType:'judgement'},
{heading:'Political division',body:'Moderate liberals formed the Octobrist Party and accepted the Manifesto, while Kadets demanded fuller constitutional government. Revolutionaries continued resistance.',question:'How did concession divide opposition?',taskType:'comparison'},
{heading:'Civil liberties',body:'Press and association briefly expanded, allowing parties and trade unions to operate more openly. Yet emergency powers and repression soon restricted these gains.',question:'How secure were the new liberties?',taskType:'judgement'},
{heading:'The Fundamental Laws',body:'Published in April 1906, the Fundamental Laws declared the Tsar’s power supreme, preserved control of ministers, foreign policy and the armed forces, and gave him power to dissolve the Duma.',question:'How did the Laws limit constitutionalism?',taskType:'explain'},
{heading:'Article 87',body:'Article 87 allowed the Tsar to issue emergency decrees when the Duma was not sitting. It became an important means of bypassing representative institutions.',question:'Why did Article 87 matter?',taskType:'judgement'},
{heading:'The two chambers',body:'The elected Duma shared legislation with the State Council, half of whose members were appointed by the Tsar. This provided a conservative barrier to reform.',question:'How did institutional design protect autocracy?',taskType:'explain'},
{heading:'The first Dumas',body:'The First and Second Dumas pressed for land and political reform and were dissolved in 1906 and 1907. Conflict showed that representative government remained subordinate to the crown.',question:'What did the early Dumas reveal?',taskType:'judgement'},
{heading:'Overall judgement',body:'The Manifesto changed political practice by creating a national assembly and legal parties, but the Fundamental Laws preserved decisive autocratic powers. Russia became a limited constitutional experiment rather than a parliamentary monarchy.',question:'Did autocracy survive?',taskType:'judgement'}];
export const manifestoFundamentalLawsTimeline={events:[{id:'jan1905',date:'January 1905',title:'Bloody Sunday',detail:'Faith in the Tsar is damaged and revolution begins.'},{id:'octstrike',date:'October 1905',title:'General strike',detail:'Transport and industry are paralysed.'},{id:'manifesto',date:'17 October 1905',title:'October Manifesto',detail:'Civil liberties and a legislative Duma are promised.'},{id:'parties',date:'Late 1905',title:'Octobrists and Kadets emerge',detail:'Liberals divide over whether the settlement is sufficient.'},{id:'moscow',date:'December 1905',title:'Moscow uprising crushed',detail:'The regime uses force after moderates withdraw.'},{id:'laws',date:'April 1906',title:'Fundamental Laws',detail:'The Tsar reasserts supreme authority.'},{id:'first',date:'July 1906',title:'First Duma dissolved',detail:'Conflict over land reform ends the first experiment.'},{id:'second',date:'June 1907',title:'Second Duma dissolved',detail:'Stolypin changes the electoral law.'}]};
export const manifestoFundamentalLawsFlashcards=[{id:'manifesto',front:'October Manifesto',back:'Promise of civil liberties, a wider franchise and legislative Duma.'},{id:'witte',front:'Witte',back:'Minister who persuaded Nicholas to make concessions.'},{id:'octobrists',front:'Octobrists',back:'Moderates who accepted the October Manifesto.'},{id:'kadets',front:'Kadets',back:'Constitutional Democrats seeking fuller parliamentary government.'},{id:'fundamental',front:'Fundamental Laws',back:'1906 settlement preserving the Tsar’s supreme powers.'},{id:'article87',front:'Article 87',back:'Power to issue emergency decrees while the Duma was not sitting.'},{id:'statecouncil',front:'State Council',back:'Upper chamber, half appointed by the Tsar.'},{id:'dissolution',front:'Dissolution',back:'Ending a Duma before its normal term.'},{id:'civil',front:'Civil liberties',back:'Freedoms of speech, assembly, conscience and association.'},{id:'franchise',front:'Franchise',back:'Rules determining who may vote.'},{id:'constitutional',front:'Constitutional monarchy',back:'Monarchy limited by enforceable law and representative institutions.'},{id:'dual',front:'Limited constitutionalism',back:'Representative institutions existing alongside dominant autocratic powers.'}];
export const manifestoFundamentalLawsQuiz=[{id:'q1',question:'When was the October Manifesto issued?',options:['17 October 1905','9 January 1905','April 1906','June 1907'],correct:'17 October 1905'},{id:'q2',question:'Who persuaded Nicholas to concede?',options:['Witte','Stolypin','Plehve','Lenin'],correct:'Witte'},{id:'q3',question:'What did the Manifesto promise?',options:['Civil liberties and a Duma','A republic','Land to every peasant','Abolition of monarchy'],correct:'Civil liberties and a Duma'},{id:'q4',question:'Who accepted the settlement?',options:['Octobrists','Bolsheviks','SR Combat Organisation','Black Hundreds only'],correct:'Octobrists'},{id:'q5',question:'Who wanted more extensive constitutional change?',options:['Kadets','Land Captains','Holy Synod','Okhrana'],correct:'Kadets'},{id:'q6',question:'What reasserted Tsarist authority in 1906?',options:['Fundamental Laws','April Theses','Treaty of Portsmouth','Zemstvo Act'],correct:'Fundamental Laws'},{id:'q7',question:'What did Article 87 permit?',options:['Emergency decrees','Universal suffrage','Duma control of ministers','Independent foreign policy'],correct:'Emergency decrees'},{id:'q8',question:'What was the State Council?',options:['Upper legislative chamber','Workers soviet','Secret police','Peasant commune'],correct:'Upper legislative chamber'},{id:'q9',question:'What happened to the First Duma?',options:['It was dissolved','It became sovereign','It abolished the Tsar','It governed until 1917'],correct:'It was dissolved'},{id:'q10',question:'Which judgement is strongest?',options:['The settlement introduced representation but preserved decisive autocratic power','Russia became a full democracy','Nothing changed at all','The Duma controlled the army'],correct:'The settlement introduced representation but preserved decisive autocratic power'}];
export const manifestoFundamentalLawsJudgement={question:'Rank the ways the post-1905 settlement preserved autocracy.',factors:[{id:'supreme',title:'Supreme autocratic authority',detail:'The Fundamental Laws reaffirmed the Tsar’s sovereignty.'},{id:'ministers',title:'Control of ministers',detail:'Ministers remained responsible to the Tsar.'},{id:'dissolution',title:'Power of dissolution',detail:'The Tsar could dismiss the Duma.'},{id:'article87',title:'Article 87',detail:'Emergency decrees bypassed the Duma.'},{id:'council',title:'State Council',detail:'The upper chamber blocked radical legislation.'},{id:'force',title:'Coercion',detail:'The army and police crushed continuing revolt.'}]};
export const manifestoFundamentalLawsAO3={question:'Evaluate each interpretation separately.',interpretations:[{historian:'Interpretation A',argument:'The October Manifesto marked a genuine constitutional turning point because lawmaking now required representation.'},{historian:'Interpretation B',argument:'The Fundamental Laws reduced the Duma to a subordinate advisory body and preserved autocracy.'},{historian:'Interpretation C',argument:'The settlement’s main success was tactical: it divided moderate liberals from revolutionary opposition.'}]};
export const manifestoFundamentalLawsPeel={question:'“The October Manifesto fundamentally limited autocracy.” Assess the validity of this view.',stretchQuestion:'Write a plan comparing promised rights, institutional reality and political practice.',scaffold:['Separate the Manifesto from the Fundamental Laws.','Use precise powers retained by the Tsar.','Assess civil liberties and the Duma.','Explain opposition division.','Reach a judgement on the extent and durability of change.']};
export const manifestoFundamentalLawsConfidence={prompt:'How confident are you judging the 1905 constitutional settlement?',leastSecureOptions:['Manifesto promises','Witte','Political parties','Fundamental Laws','Article 87','Dumas','Overall judgement'],scale:[1,2,3,4,5]};
export const manifestoFundamentalLawsFallbacks:Record<string,any>={lesson_content:{sections:manifestoFundamentalLawsLessonSections},timeline:manifestoFundamentalLawsTimeline,flashcards:{cards:manifestoFundamentalLawsFlashcards},quiz:{questions:manifestoFundamentalLawsQuiz},judgement_ranking:manifestoFundamentalLawsJudgement,ao3_interpretation:manifestoFundamentalLawsAO3,peel_response:manifestoFundamentalLawsPeel,confidence_exit_ticket:manifestoFundamentalLawsConfidence};