import { pathwayOptions, pathwayRegistry, type PathwayConfig } from './pathwayRegistry';

const unitTitle='Stalinist transformation and dictatorship, 1928–41';
export const unit7Pathways:PathwayConfig[]=[
{pathwaySlug:'great-turn-end-nep',title:'The Great Turn and the end of NEP',lessonTitle:'Why did Stalin abandon NEP and launch the Great Turn?',subtitle:'The grain crisis, ideology, security, the defeat of the Right and the move to command planning',yearGroup:'Y13',courseWeek:1,unitNumber:7,unitTitle,mainFocus:'Reasons for the end of NEP and the transition to Stalinist economic transformation',writtenFocus:'Causal judgement on the Great Turn',writtenFocusType:'ESSAY_PLAN',breadthLenses:['economy','governance','ideology','individuals'],status:'ready',routeBase:'/student/lesson/great-turn-end-nep'},
{pathwaySlug:'collectivisation',title:'Collectivisation',lessonTitle:'How successful was Stalin’s collectivisation of agriculture?',subtitle:'Aims, dekulakisation, resistance, famine and state control of the countryside',yearGroup:'Y13',courseWeek:2,unitNumber:7,unitTitle,mainFocus:'Political, economic and human consequences of collectivisation',writtenFocus:'Success and failure judgement',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['economy','society','governance','opposition'],status:'ready',routeBase:'/student/lesson/collectivisation'},
{pathwaySlug:'five-year-plans',title:'The Five-Year Plans',lessonTitle:'How far did the Five-Year Plans transform the Soviet economy?',subtitle:'Gosplan, heavy industry, labour discipline, Stakhanovism, achievement and cost',yearGroup:'Y13',courseWeek:3,unitNumber:7,unitTitle,mainFocus:'Industrial growth, planning, labour and living standards',writtenFocus:'Economic success essay judgement',writtenFocusType:'ESSAY_PLAN',breadthLenses:['economy','society','governance','individuals'],status:'ready',routeBase:'/student/lesson/five-year-plans'},
{pathwaySlug:'stalinist-society-culture',title:'Stalinist society and culture',lessonTitle:'How far did Stalin transform Soviet society and culture?',subtitle:'Urbanisation, education, women, family, Socialist Realism, religion and nationalities',yearGroup:'Y13',courseWeek:4,unitNumber:7,unitTitle,mainFocus:'Social opportunity, hierarchy, cultural control and everyday experience',writtenFocus:'Change and continuity judgement',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['society','ideology','economy','governance'],status:'ready',routeBase:'/student/lesson/stalinist-society-culture'},
{pathwaySlug:'great-terror',title:'The Great Terror',lessonTitle:'Why did the Great Terror develop and what did it achieve?',subtitle:'Kirov, show trials, mass operations, the NKVD, the army purge and consequences',yearGroup:'Y13',courseWeek:5,unitNumber:7,unitTitle,mainFocus:'Causes, mechanisms, scale and consequences of repression',writtenFocus:'Causation and responsibility essay',writtenFocusType:'AO3_INTERPRETATIONS',breadthLenses:['governance','opposition','individuals','society'],status:'ready',routeBase:'/student/lesson/great-terror'},
{pathwaySlug:'stalin-dictatorship-control',title:'Stalin’s dictatorship and control',lessonTitle:'How did Stalin establish and maintain dictatorship by 1941?',subtitle:'Party machinery, patronage, terror, propaganda, the cult and participation',yearGroup:'Y13',courseWeek:6,unitNumber:7,unitTitle,mainFocus:'The foundations, reach and limits of Stalin’s personal dictatorship',writtenFocus:'Relative importance of methods of control',writtenFocusType:'ESSAY_PLAN',breadthLenses:['governance','ideology','opposition','individuals'],status:'ready',routeBase:'/student/lesson/stalin-dictatorship-control'}
];
for(const config of unit7Pathways){
 pathwayRegistry[config.pathwaySlug]=config;
 if(!pathwayOptions.some(existing=>existing.pathwaySlug===config.pathwaySlug)) pathwayOptions.push(config);
}
pathwayOptions.sort((a,b)=>a.yearGroup!==b.yearGroup?a.yearGroup.localeCompare(b.yearGroup):a.unitNumber!==b.unitNumber?a.unitNumber-b.unitNumber:a.courseWeek-b.courseWeek);