import { pathwayOptions, pathwayRegistry, type PathwayConfig } from './pathwayRegistry';

const unitTitle='Khrushchev and the USSR, 1953–64';
export const unit9Pathways:PathwayConfig[]=[
{pathwaySlug:'succession-after-stalin',title:'The succession after Stalin',lessonTitle:'Why did Khrushchev emerge as Soviet leader after Stalin?',subtitle:'Collective leadership, Beria, Malenkov, Party power and Khrushchev’s political manoeuvring',yearGroup:'Y13',courseWeek:1,unitNumber:9,unitTitle,mainFocus:'The post-Stalin power struggle and Khrushchev’s emergence',writtenFocus:'Causal judgement on Khrushchev’s rise',writtenFocusType:'ESSAY_PLAN',breadthLenses:['governance','individuals','opposition','ideology'],status:'ready',routeBase:'/student/lesson/succession-after-stalin'},
{pathwaySlug:'de-stalinisation-secret-speech',title:'De-Stalinisation and the Secret Speech',lessonTitle:'How far did Khrushchev dismantle Stalinism?',subtitle:'The thaw, prisoner releases, the Secret Speech, limits and consequences',yearGroup:'Y13',courseWeek:2,unitNumber:9,unitTitle,mainFocus:'The extent, motives and limits of de-Stalinisation',writtenFocus:'Change and continuity judgement',writtenFocusType:'AO3_INTERPRETATIONS',breadthLenses:['governance','ideology','society','individuals'],status:'ready',routeBase:'/student/lesson/de-stalinisation-secret-speech'},
{pathwaySlug:'khrushchev-party-control-opposition',title:'Party control and opposition',lessonTitle:'How secure was Khrushchev’s political position?',subtitle:'The Anti-Party Group, Party reform, nomenklatura, dissent and continued coercion',yearGroup:'Y13',courseWeek:3,unitNumber:9,unitTitle,mainFocus:'Khrushchev’s control of Party and state and the limits of liberalisation',writtenFocus:'Security of leadership judgement',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['governance','opposition','ideology','individuals'],status:'ready',routeBase:'/student/lesson/khrushchev-party-control-opposition'},
{pathwaySlug:'khrushchev-agriculture',title:'Agriculture under Khrushchev',lessonTitle:'How successful were Khrushchev’s agricultural reforms?',subtitle:'Virgin Lands, maize, collective farms, incentives, procurement and the 1963 grain crisis',yearGroup:'Y13',courseWeek:4,unitNumber:9,unitTitle,mainFocus:'Agricultural experimentation, achievement, instability and failure',writtenFocus:'Success and failure essay',writtenFocusType:'ESSAY_PLAN',breadthLenses:['economy','society','governance','individuals'],status:'ready',routeBase:'/student/lesson/khrushchev-agriculture'},
{pathwaySlug:'khrushchev-economy-society-culture',title:'Economy, society and culture',lessonTitle:'How far did life improve under Khrushchev?',subtitle:'Industrial reform, consumer goods, housing, education, women, religion and the cultural thaw',yearGroup:'Y13',courseWeek:5,unitNumber:9,unitTitle,mainFocus:'Economic reform, living standards, social policy and cultural change',writtenFocus:'Living standards and freedom judgement',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['economy','society','ideology','governance'],status:'ready',routeBase:'/student/lesson/khrushchev-economy-society-culture'},
{pathwaySlug:'fall-of-khrushchev-1964',title:'The fall of Khrushchev',lessonTitle:'Why was Khrushchev removed from power in 1964?',subtitle:'Economic weaknesses, policy failures, Party resentment, leadership style and the October coup',yearGroup:'Y13',courseWeek:6,unitNumber:9,unitTitle,mainFocus:'The causes of Khrushchev’s removal and the overall balance of his leadership',writtenFocus:'25-mark causal judgement',writtenFocusType:'ESSAY_PLAN',breadthLenses:['governance','economy','opposition','individuals'],status:'ready',routeBase:'/student/lesson/fall-of-khrushchev-1964'}
];
for(const config of unit9Pathways){pathwayRegistry[config.pathwaySlug]=config;if(!pathwayOptions.some(existing=>existing.pathwaySlug===config.pathwaySlug))pathwayOptions.push(config);}
pathwayOptions.sort((a,b)=>a.yearGroup!==b.yearGroup?a.yearGroup.localeCompare(b.yearGroup):a.unitNumber!==b.unitNumber?a.unitNumber-b.unitNumber:a.courseWeek-b.courseWeek);
