import { pathwayRegistry, type PathwayConfig } from './pathwayRegistry';
import './unit9RegistryActivation';

const unitTitle='The Soviet Union at war and High Stalinism, 1941–53';
export const unit8Pathways:PathwayConfig[]=[
{pathwaySlug:'barbarossa-stalin-leadership',title:'Barbarossa and Stalin’s wartime leadership',lessonTitle:'How effective was Stalin’s leadership during the Great Patriotic War?',subtitle:'The shock of invasion, central command, military learning and patriotic mobilisation',yearGroup:'Y13',courseWeek:1,unitNumber:8,unitTitle,mainFocus:'Stalin’s responsibility for disaster, wartime adaptation and contribution to victory',writtenFocus:'Leadership and victory judgement',writtenFocusType:'ESSAY_PLAN',breadthLenses:['governance','individuals','opposition','ideology'],status:'ready',routeBase:'/student/lesson/barbarossa-stalin-leadership'},
{pathwaySlug:'wartime-politics-opposition-nationalities',title:'Wartime politics, opposition and nationalities',lessonTitle:'How did the Soviet regime maintain political control during the war?',subtitle:'Emergency government, coercion, collaboration, deportation and the nationalities',yearGroup:'Y13',courseWeek:2,unitNumber:8,unitTitle,mainFocus:'Changes and continuities in dictatorship, opposition and nationality policy',writtenFocus:'Methods of wartime control',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['governance','opposition','society','ideology'],status:'ready',routeBase:'/student/lesson/wartime-politics-opposition-nationalities'},
{pathwaySlug:'wartime-economy-mobilisation',title:'The wartime economy and mobilisation',lessonTitle:'Why was the Soviet wartime economy able to sustain victory?',subtitle:'Industrial evacuation, command planning, labour, agriculture and Lend-Lease',yearGroup:'Y13',courseWeek:3,unitNumber:8,unitTitle,mainFocus:'Economic mobilisation, production, logistics and the human cost of total war',writtenFocus:'Reasons for economic success',writtenFocusType:'ESSAY_PLAN',breadthLenses:['economy','society','governance','individuals'],status:'ready',routeBase:'/student/lesson/wartime-economy-mobilisation'},
{pathwaySlug:'soviet-society-at-war',title:'Soviet society at war',lessonTitle:'How far did war transform Soviet society?',subtitle:'Occupation, workers, peasants, women, religion, partisans and morale',yearGroup:'Y13',courseWeek:4,unitNumber:8,unitTitle,mainFocus:'Social sacrifice, mobilisation, cultural concessions and continuity under wartime pressure',writtenFocus:'Change and continuity judgement',writtenFocusType:'JUDGEMENT_TASK',breadthLenses:['society','economy','ideology','opposition'],status:'ready',routeBase:'/student/lesson/soviet-society-at-war'},
{pathwaySlug:'victory-impact-1945',title:'Victory and its impact',lessonTitle:'How far did victory transform Stalin and the Soviet Union?',subtitle:'Superpower status, destruction, returnees, public expectations and renewed suspicion',yearGroup:'Y13',courseWeek:5,unitNumber:8,unitTitle,mainFocus:'Political, social, economic and international consequences of victory',writtenFocus:'Impact of war essay judgement',writtenFocusType:'ESSAY_PLAN',breadthLenses:['governance','society','economy','individuals'],status:'ready',routeBase:'/student/lesson/victory-impact-1945'},
{pathwaySlug:'high-stalinism-1945-53',title:'High Stalinism, 1945–53',lessonTitle:'Why did repression and ideological control revive after 1945?',subtitle:'Zhdanovshchina, reconstruction, the Leningrad Affair, anti-cosmopolitanism and the Doctors’ Plot',yearGroup:'Y13',courseWeek:6,unitNumber:8,unitTitle,mainFocus:'Post-war reconstruction, renewed terror, ideological control and Stalin’s final legacy',writtenFocus:'Causes and character of High Stalinism',writtenFocusType:'AO3_INTERPRETATIONS',breadthLenses:['governance','opposition','ideology','economy'],status:'ready',routeBase:'/student/lesson/high-stalinism-1945-53'}
];
for(const config of unit8Pathways){pathwayRegistry[config.pathwaySlug]=config;}
