import { pathwayRegistry } from './pathwayRegistry';

const unitTitle='Lenin and the emergence of Communist dictatorship';
const configs=[
{pathwaySlug:'bolshevik-consolidation',title:'Bolshevik consolidation and opposition',lessonTitle:'How did the Bolsheviks consolidate power after October 1917?',subtitle:'Political opposition, Cheka, Red Terror, Church, nationalities and party dictatorship',yearGroup:'Y13' as const,courseWeek:2,unitNumber:6,unitTitle,mainFocus:'Political opposition, coercion, institutional control and one-party dictatorship',writtenFocus:'Repression and consolidation judgement',writtenFocusType:'JUDGEMENT_TASK' as const,breadthLenses:['governance','opposition','ideology','individuals'] as const,status:'ready' as const,routeBase:'/student/lesson/bolshevik-consolidation'},
{pathwaySlug:'civil-war',title:'The Russian Civil War',lessonTitle:'Why did the Reds win the Russian Civil War?',subtitle:'Reds, Whites, Trotsky, geography, organisation and foreign intervention',yearGroup:'Y13' as const,courseWeek:3,unitNumber:6,unitTitle,mainFocus:'Red strengths, White weaknesses, geography, leadership and mobilisation',writtenFocus:'Causes of Red victory',writtenFocusType:'ESSAY_PLAN' as const,breadthLenses:['governance','opposition','economy','society','individuals'] as const,status:'ready' as const,routeBase:'/student/lesson/civil-war'},
{pathwaySlug:'war-communism',title:'War Communism',lessonTitle:'How successful was War Communism?',subtitle:'Nationalisation, requisitioning, labour, economic collapse and resistance',yearGroup:'Y13' as const,courseWeek:4,unitNumber:6,unitTitle,mainFocus:'Emergency mobilisation, ideology, economic collapse and political resistance',writtenFocus:'Success and failure judgement',writtenFocusType:'JUDGEMENT_TASK' as const,breadthLenses:['economy','society','governance','ideology'] as const,status:'ready' as const,routeBase:'/student/lesson/war-communism'},
{pathwaySlug:'nep',title:'The New Economic Policy',lessonTitle:'How successful was the New Economic Policy?',subtitle:'Tax in kind, mixed economy, recovery, Nepmen and the Scissors Crisis',yearGroup:'Y13' as const,courseWeek:5,unitNumber:6,unitTitle,mainFocus:'Economic retreat, recovery, ideological compromise and political control',writtenFocus:'Short-term success vs long-term weakness',writtenFocusType:'ESSAY_PLAN' as const,breadthLenses:['economy','society','governance','ideology'] as const,status:'ready' as const,routeBase:'/student/lesson/nep'},
{pathwaySlug:'struggle-after-lenin',title:'The struggle for power after Lenin',lessonTitle:'Why did Stalin win the power struggle after Lenin?',subtitle:'Contenders, General Secretaryship, alliances, ideology and rivals’ mistakes',yearGroup:'Y13' as const,courseWeek:6,unitNumber:6,unitTitle,mainFocus:'Party machinery, ideological positioning, alliances and opposition weakness',writtenFocus:'25-mark causal judgement',writtenFocusType:'ESSAY_PLAN' as const,breadthLenses:['governance','opposition','ideology','individuals'] as const,status:'ready' as const,routeBase:'/student/lesson/struggle-after-lenin'}
];
for(const config of configs){pathwayRegistry[config.pathwaySlug]=config as any;}
