import type { SubjectPathway } from '@/subjects/types';

export const psychologyAqaPathways: SubjectPathway[] = [
  {
    pathwaySlug: 'psychology-social-influence-conformity',
    title: 'Conformity',
    lessonTitle: 'Why do people conform?',
    subtitle: 'Types of conformity, normative and informational social influence, and variables affecting conformity in Asch research.',
    yearGroup: 'Y12',
    courseWeek: 1,
    unitNumber: 1,
    unitTitle: 'Social influence',
    status: 'ready',
    routeBase: '/student/lesson/psychology-social-influence-conformity',
    metadata: { skillFocus: ['knowledge', 'application', 'evaluation'], specificationSection: '3.1.1 Social influence' },
  },
  {
    pathwaySlug: 'psychology-memory-models',
    title: 'Models of memory',
    lessonTitle: 'How do psychologists explain the structure of memory?',
    subtitle: 'A pilot pathway for knowledge, application and evaluation activities.',
    yearGroup: 'Y12',
    courseWeek: 2,
    unitNumber: 2,
    unitTitle: 'Memory',
    status: 'planned',
    routeBase: '/student/lesson/psychology-memory-models',
    metadata: { skillFocus: ['knowledge', 'application', 'evaluation'] },
  },
  {
    pathwaySlug: 'psychology-memory-eyewitness',
    title: 'Eyewitness testimony',
    lessonTitle: 'What affects the accuracy of eyewitness testimony?',
    subtitle: 'A pilot pathway combining retrieval, application and written evaluation.',
    yearGroup: 'Y12',
    courseWeek: 3,
    unitNumber: 2,
    unitTitle: 'Memory',
    status: 'planned',
    routeBase: '/student/lesson/psychology-memory-eyewitness',
    metadata: { skillFocus: ['knowledge', 'application', 'evaluation'] },
  },
];
