import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireRoles } from '@/lib/auth/access';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import styles from './page.module.css';

type Tab = 'overview' | 'students' | 'assignments';
type ProgressStatus = 'not_started' | 'in_progress' | 'complete';
type Assignment = { id: string; title: string; lesson_title: string; due_at: string | null; status: string; created_at: string; assignment_recipients: { student_id: string; status: string }[] | null };
type Progress = { assignment_id: string; student_id: string; status: ProgressStatus; progress_percent: number; last_activity_at: string | null };
function relation<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] ?? null : value; }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : 'No activity yet'; }
function dueState(value: string | null) { if (!value) return 'No deadline'; const difference = new Date(value).getTime() - Date.now(); if (difference < 0) return 'Overdue'; if (difference <= 48 * 60 * 60 * 1000) return 'Due soon'; return `Due ${formatDate(value)}`; }
export const dynamic = 'force-dynamic'; export const revalidate = 0;
export default async function ClassWorkspacePage({ params, searchParams }: { params: Promise<{ classId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
 const auth=await requireRoles(['teacher','admin']); const supabase=await createServerSupabaseClient(); const {classId}=await params; const query=await searchParams; if(!auth||!supabase) notFound();
 const requestedTab=typeof query.tab==='string'?query.tab:'overview'; const activeTab:Tab=['overview','students','assignments'].includes(requestedTab)?requestedTab as Tab:'overview'; const search=typeof query.search==='string'?query.search.trim().toLowerCase():''; const filter=typeof query.filter==='string'?query.filter:'all';
 const {data:teacherLink}=await supabase.from('class_teachers').select('class_id, teaching_classes(id, name, academic_year, join_code, schools(name))').eq('teacher_id',auth.userId).eq('class_id',classId).maybeSingle(); const teachingClass=relation((teacherLink as any)?.teaching_classes); if(!teachingClass) notFound();
 const [{data:memberships,error:membershipError},{data:assignmentRows,error:assignmentError}]=await Promise.all([supabase.from('class_memberships').select('student_id').eq('class_id',classId).eq('status','active'),supabase.from('classroom_assignments').select('id, title, lesson_title, due_at, status, created_at, assignment_recipients(student_id, status)').eq('class_id',classId).order('created_at',{ascending:false})]);
 const studentIds=(memberships??[]).map((r:any)=>r.student_id); const assignments=(assignmentRows??[]) as Assignment[]; const assignmentIds=assignments.map(a=>a.id);
 const [profilesResult,progressResult,confidenceResult]=await Promise.all([studentIds.length?supabase.from('profiles').select('id, full_name').in('id',studentIds):Promise.resolve({data:[],error:null}),assignmentIds.length?supabase.from('assignment_progress').select('assignment_id, student_id, status, progress_percent, last_activity_at').in('assignment_id',assignmentIds):Promise.resolve({data:[],error:null}),assignmentIds.length?supabase.from('student_activity_progress').select('assignment_id, student_id, confidence, last_saved_at').in('assignment_id',assignmentIds).not('confidence','is',null).order('last_saved_at',{ascending:false}):Promise.resolve({data:[],error:null})]);
 const profiles=new Map((profilesResult.data??[]).map((p:any)=>[p.id,p.full_name?.trim()||'Student'])); const progressRows=(progressResult.data??[]) as Progress[]; const progressByKey=new Map(progressRows.map(r=>[`${r.assignment_id}:${r.student_id}`,r])); const confidenceByKey=new Map<string,number>(); (confidenceResult.data??[]).forEach((r:any)=>{const k=`${r.assignment_id}:${r.student_id}`;if(!confidenceByKey.has(k)&&r.confidence!==null)confidenceByKey.set(k,r.confidence)});
 const publishedAssignments=assignments.filter(a=>a.status==='published'); const archivedAssignments=assignments.filter(a=>a.status!=='published');
 const students=studentIds.map(studentId=>{const assigned=publishedAssignments.filter(a=>(a.assignment_recipients??[]).some(r=>r.student_id===studentId&&r.status==='assigned'));const rows=assigned.map(a=>progressByKey.get(`${a.id}:${studentId}`));const completed=rows.filter(r=>r?.status==='complete').length;const average=assigned.length?Math.round(rows.reduce((s,r)=>s+(r?.progress_percent??0),0)/assigned.length):0;const latest=rows.map(r=>r?.last_activity_at).filter((v):v is string=>Boolean(v)).sort().at(-1)??null;let needsAttention=false;assigned.forEach(a=>{const k=`${a.id}:${studentId}`;const r=progressByKey.get(k);const c=confidenceByKey.get(k);const d=a.due_at?new Date(a.due_at).getTime()-Date.now():null;if((!r||r.status==='not_started')&&d!==null&&d<=48*60*60*1000)needsAttention=true;if(c!==undefined&&c<=2)needsAttention=true;if(r?.status==='in_progress'&&r.last_activity_at&&Date.now()-new Date(r.last_activity_at).getTime()>=3*24*60*60*1000)needsAttention=true});const status:ProgressStatus=assigned.length>0&&completed===assigned.length?'complete':rows.some(r=>r&&r.status!=='not_started')?'in_progress':'not_started';return{studentId,name:profiles.get(studentId)??'Student',assignments:assigned.length,completed,average,latest,needsAttention,status}}).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
 const visibleStudents=students.filter(s=>(!search||String(s.name).toLowerCase().includes(search))&&(filter==='all'||(filter==='attention'&&s.needsAttention)||filter===s.status));
 const assignmentCards=publishedAssignments.map(a=>{const recipients=(a.assignment_recipients??[]).filter(r=>r.status==='assigned');const rows=recipients.map(r=>progressByKey.get(`${a.id}:${r.student_id}`));const completed=rows.filter(r=>r?.status==='complete').length;const average=recipients.length?Math.round(rows.reduce((s,r)=>s+(r?.progress_percent??0),0)/recipients.length):0;return{assignment:a,recipients:recipients.length,completed,average}}); const attentionStudents=students.filter(s=>s.needsAttention); const completedToday=progressRows.filter(r=>r.status==='complete'&&r.last_activity_at&&new Date(r.last_activity_at).toDateString()===new Date().toDateString()).length; const loadError=membershipError||assignmentError||profilesResult.error||progressResult.error||confidenceResult.error;
 const setWorkHref=`/teacher/set-study?classId=${encodeURIComponent(classId)}`;
 return <main className={styles.workspace}><section className={styles.classHeader}><div><Link className={styles.backLink} href="/teacher/classes">← All classes</Link><p className={styles.eyebrow}>{relation(teachingClass.schools)?.name||'Teaching class'}</p><h2>{teachingClass.name}</h2><p>{teachingClass.academic_year||'Academic year not set'} · Join code <strong>{teachingClass.join_code}</strong></p></div><div className={styles.headerActions}><Link className={styles.primaryAction} href={setWorkHref}>Set work</Link></div></section>{loadError&&<section className={styles.notice} role="alert"><strong>Some class information could not be loaded.</strong><span>{loadError.message}</span></section>}
 <section className={styles.trackerCallout}><div><p className={styles.eyebrow}>Progress trackers</p><h3>Class and individual progress at a glance</h3><p>See Complete, Incomplete and Not attempted assignment history across the class, open individual student trackers, and download the data when you need it.</p></div><Link className={styles.primaryAction} href={`/teacher/classes/${classId}/tracking`}>Open progress trackers →</Link></section>
 <nav className={styles.tabs} aria-label={`${teachingClass.name} workspace`}><Link href={`/teacher/classes/${classId}`} className={activeTab==='overview'?styles.activeTab:styles.tab}>Overview</Link><Link href={`/teacher/classes/${classId}?tab=students`} className={activeTab==='students'?styles.activeTab:styles.tab}>Students ({studentIds.length})</Link><Link href={`/teacher/classes/${classId}?tab=assignments`} className={activeTab==='assignments'?styles.activeTab:styles.tab}>Assignments ({publishedAssignments.length})</Link></nav>
 {activeTab==='overview'&&<><section className={styles.metrics}><article><span>Students</span><strong>{studentIds.length}</strong></article><article><span>Active assignments</span><strong>{publishedAssignments.length}</strong></article><article className={attentionStudents.length?styles.attentionMetric:''}><span>Needs attention</span><strong>{attentionStudents.length}</strong></article></section><section className={styles.twoColumn}><section className={styles.panel}><header><div><h3>Needs attention</h3><p>Students with deadline, confidence or stalled-progress signals.</p></div><Link href={`/teacher/classes/${classId}?tab=students&filter=attention`}>View students</Link></header>{attentionStudents.length===0?<div className={styles.empty}><strong>No immediate concerns</strong><p>No students currently meet the attention rules.</p></div>:attentionStudents.slice(0,5).map(s=><article className={styles.row} key={s.studentId}><div><strong>{s.name}</strong><p>{s.completed}/{s.assignments} assignments complete</p></div><Link href={`/teacher/classes/${classId}/students/${s.studentId}`}>Review</Link></article>)}</section><section className={styles.panel}><header><div><h3>Recent assignments</h3><p>{completedToday} student completions today.</p></div><Link href={`/teacher/classes/${classId}?tab=assignments`}>View assignments</Link></header>{assignmentCards.length===0?<div className={styles.empty}><strong>No active assignments</strong><p>Set work to begin collecting progress.</p></div>:assignmentCards.slice(0,4).map(({assignment,completed,recipients})=><article className={styles.row} key={assignment.id}><div><strong>{assignment.title}</strong><p>{completed}/{recipients} complete</p></div><Link href={`/teacher/assignments/${assignment.id}?tab=students`}>Responses</Link></article>)}</section></section></>}
 {activeTab==='students'&&<section className={styles.panel}><header><div><h3>Students</h3><p>Open a student to see their complete history, notes and assignment evidence.</p></div></header><form className={styles.filters} method="get"><input type="hidden" name="tab" value="students"/><input name="search" defaultValue={typeof query.search==='string'?query.search:''} placeholder="Search students" aria-label="Search students"/><select name="filter" defaultValue={filter} aria-label="Filter students"><option value="all">All students</option><option value="attention">Needs attention</option><option value="not_started">Not attempted</option><option value="in_progress">Incomplete</option><option value="complete">Complete</option></select><button type="submit">Apply</button></form><div className={styles.tableHeader}><span>Student</span><span>Assignments</span><span>Average</span><span>Status</span></div>{visibleStudents.length===0?<div className={styles.empty}><strong>No students match</strong><p>Change the search or filter.</p></div>:visibleStudents.map(s=><Link href={`/teacher/classes/${classId}/students/${s.studentId}`} className={styles.studentRow} key={s.studentId}><div><strong>{s.name}</strong><small>{s.latest?`Last active ${formatDate(s.latest)}`:'No saved activity'}</small></div><span>{s.completed}/{s.assignments}</span><span>{s.average}%</span><span className={s.needsAttention?styles.warning:styles.status}>{s.needsAttention?'Needs attention':s.status==='complete'?'Complete':s.status==='in_progress'?'Incomplete':'Not attempted'}</span></Link>)}</section>}
 {activeTab==='assignments'&&<section className={styles.panel}><header><div><h3>Assignments & responses</h3><p>Open an assignment to review student responses and completion, or use Progress trackers for the whole-class history.</p></div><Link href={setWorkHref}>New assignment</Link></header>{assignmentCards.length===0?<div className={styles.empty}><strong>No published assignments</strong><p>Create the first assignment for this class.</p></div>:assignmentCards.map(({assignment,recipients,completed,average})=><article className={styles.assignmentRow} key={assignment.id}><div><strong>{assignment.title}</strong><p>{assignment.lesson_title} · {dueState(assignment.due_at)}</p><div className={styles.progressTrack}><span style={{width:`${average}%`}}/></div></div><div className={styles.assignmentStats}><span>{completed}/{recipients} complete</span><span>{average}% average</span><Link href={`/teacher/assignments/${assignment.id}?tab=students`}>Student responses</Link></div></article>)}{archivedAssignments.length>0&&<details className={styles.archived}><summary>Archived assignments ({archivedAssignments.length})</summary>{archivedAssignments.map(a=><div key={a.id}><strong>{a.title}</strong><span>{a.lesson_title}</span><Link href={`/teacher/assignments/${a.id}`}>Open</Link></div>)}</details>}</section>}</main>;
}
