import { recallQuestions as coreRecallQuestions, recallTopics } from './questions';
import { additionalRecallQuestions } from './questions-expanded';
import { depthRecallQuestions } from './questions-depth';

export type { RecallQuestion, RecallQuestionType, RecallTopic } from './questions';
export { recallTopics };

const rebalance = (question: (typeof additionalRecallQuestions)[number]) => {
  if (question.id === 'k-23') return { ...question, options: ['Frequent reorganisations upset officials', 'Repeated promotions reassured officials', 'Higher salaries satisfied officials', 'Stable ministries protected officials'], correctOption: 0, answerLabel: 'Frequent reorganisations upset officials' };
  if (question.id === 'a2-57') return { ...question, options: ['They provided experience of elected local service', 'They created a fully elected national government', 'They placed military command under local councils', 'They made government ministers locally accountable'], correctOption: 0, answerLabel: 'They provided experience of elected local service' };
  if (question.id === 'a3-41') return { ...question, options: ['Exports continued while rural communities faced hardship', 'Imports continued while urban factories faced shortages', 'Tariffs fell while industrial employers cut taxation', 'Railways closed while landowners abandoned farming'], correctOption: 0, answerLabel: 'Exports continued while rural communities faced hardship' };
  if (question.id === 'n2-53') return { ...question, options: ['The franchise favoured conservative property owners', 'The franchise favoured radical urban workers', 'The Tsar surrendered control over ministers', 'The Duma controlled appointments to the army'], correctOption: 0, answerLabel: 'The franchise favoured conservative property owners' };
  if (question.id === 'n2-65') return { ...question, options: ['Military failures became associated personally with Nicholas', 'Duma successes became associated personally with Nicholas', 'Economic recovery became associated personally with Nicholas', 'Court stability became associated personally with Nicholas'], correctOption: 0, answerLabel: 'Military failures became associated personally with Nicholas' };
  if (question.id === 'n2-85') return { ...question, options: ['They believed Nicholas was damaging the effectiveness of the war effort', 'They believed Nicholas had strengthened the effectiveness of the war effort', 'They believed the Duma had already ended Russia’s participation in the war', 'They believed Alexandra had restored effective control over the army'], correctOption: 0, answerLabel: 'They believed Nicholas was damaging the effectiveness of the war effort' };
  if (question.id === 'n2-89') return { ...question, options: ['War magnified existing political, economic and social weaknesses', 'Industrial growth removed most political and social weaknesses', 'Duma reform transferred effective sovereignty away from the Tsar', 'Army loyalty remained strong enough to contain the political crisis'], correctOption: 0, answerLabel: 'War magnified existing political, economic and social weaknesses' };
  if (question.id === 'l-39') return { ...question, options: ['It removed an elected rival source of political authority', 'It created a stronger elected source of political authority', 'It transferred political authority back to the former Tsar', 'It placed political authority under independent courts'], correctOption: 0, answerLabel: 'It removed an elected rival source of political authority' };
  if (question.id === 'l-43') return { ...question, options: ['They controlled the central heartland and main railway network', 'They controlled the distant borderlands and most foreign ports', 'They relied mainly on Allied supply routes across Siberia', 'They held only scattered rural areas away from major cities'], correctOption: 0, answerLabel: 'They controlled the central heartland and main railway network' };
  if (question.id === 'l-45') return { ...question, options: ['It let the Reds portray the Whites as dependent on foreign powers', 'It let the Whites portray the Reds as dependent on foreign powers', 'It removed the importance of nationalism from Bolshevik propaganda', 'It gave every White army a single and unified political programme'], correctOption: 0, answerLabel: 'It let the Reds portray the Whites as dependent on foreign powers' };
  if (question.id === 'l-49') return { ...question, options: ['The sailors had previously been strong supporters of revolution', 'The sailors had always been leading supporters of the monarchy', 'The sailors were fighting only for restoration of noble privilege', 'The sailors were demanding a return to full War Communism'], correctOption: 0, answerLabel: 'The sailors had previously been strong supporters of revolution' };
  if (question.id === 'l-53') return { ...question, options: ['Organised opposition groups within the Communist Party', 'Private trading groups operating under the New Economic Policy', 'Military units operating independently of the Red Army', 'National republics operating outside the Soviet federation'], correctOption: 0, answerLabel: 'Organised opposition groups within the Communist Party' };
  if (question.id === 's-29') return { ...question, options: ['Permanent Revolution versus Socialism in One Country', 'Permanent War Communism versus a full return to capitalism', 'Immediate collectivisation versus restoration of private estates', 'Abolition of the Party versus restoration of the Constituent Assembly'], correctOption: 0, answerLabel: 'Permanent Revolution versus Socialism in One Country' };
  if (question.id === 's-33') return { ...question, options: ['He formed shifting alliances while controlling party organisation', 'He won a competitive national election against all major rivals', 'He gained control by commanding the strongest White army forces', 'He dissolved the Communist Party and ruled outside its structures'], correctOption: 0, answerLabel: 'He formed shifting alliances while controlling party organisation' };
  if (question.id === 's-35') return { ...question, options: ['A rapid shift to collectivisation and planned industrialisation', 'A rapid shift back to private farming and market industrialisation', 'A gradual restoration of noble estates and private factories', 'A gradual transfer of economic planning to local elected councils'], correctOption: 0, answerLabel: 'A rapid shift to collectivisation and planned industrialisation' };
  if (question.id === 's-63') return { ...question, options: ['The Party and security apparatus still controlled political life', 'Opposition parties gained equal access to elections and the press', 'The security police lost the power to arrest political opponents', 'Regional soviets became independent of central party authority'], correctOption: 0, answerLabel: 'The Party and security apparatus still controlled political life' };
  if (question.id === 's-77') return { ...question, options: ['A post-war campaign imposing tighter cultural and ideological control', 'A post-war campaign expanding political and artistic pluralism', 'A post-war campaign transferring industry to private ownership', 'A post-war campaign reducing central control over education'], correctOption: 0, answerLabel: 'A post-war campaign imposing tighter cultural and ideological control' };
  if (question.id === 's-81') return { ...question, options: ['An alleged medical conspiracy against Soviet leaders', 'A proposed reform of the Soviet health service', 'An alleged military conspiracy against Party officials', 'A proposed expansion of hospital provision'], correctOption: 0, answerLabel: 'An alleged medical conspiracy against Soviet leaders' };
  if (question.id === 's-83') return { ...question, options: ['They were collectively accused of disloyalty or collaboration', 'They were collectively rewarded for military and political loyalty', 'They were transferred voluntarily to new industrial settlements', 'They were exempted from wartime controls because of regional autonomy'], correctOption: 0, answerLabel: 'They were collectively accused of disloyalty or collaboration' };
  if (question.id === 'k-35') return { ...question, options: ['One Day in the Life of Ivan Denisovich', 'The Gulag Archipelago by Solzhenitsyn', 'Doctor Zhivago by Boris Pasternak', 'The Young Guard by Alexander Fadeyev'], correctOption: 0, answerLabel: 'One Day in the Life of Ivan Denisovich' };
  if (question.id === 'k-49') return { ...question, options: ['Living standards generally improved compared with the Stalin era', 'Living standards generally declined compared with the Stalin era', 'Consumer production was abandoned in favour of military output only', 'Housing construction stopped as collective agriculture expanded'], correctOption: 0, answerLabel: 'Living standards generally improved compared with the Stalin era' };
  if (question.id === 'k-53') return { ...question, options: ['Repeated reorganisations threatened officials’ positions and influence', 'Repeated promotions strengthened officials’ positions and influence', 'Stable administrative structures removed officials’ political concerns', 'Higher agricultural output removed officials’ objections to reform'], correctOption: 0, answerLabel: 'Repeated reorganisations threatened officials’ positions and influence' };
  return question;
};

export const recallQuestions = [...coreRecallQuestions, ...additionalRecallQuestions.map(rebalance), ...depthRecallQuestions.map(rebalance)];
export const recallQuestionById = new Map(recallQuestions.map((question) => [question.id, question]));
export const recallTopicById = new Map(recallTopics.map((topic) => [topic.id, topic]));
